Fix closestTo should possibly return undefined
date-fns/date-fns pull request #1933
Opened 2020-09-02 13:20 UTC by V-Gutierrez

#1915

2020-09-02 13:42 UTC, kossnocorp requested changes
Hey, thank you for the fix, but it won't have an effect because we generate typings from JSDoc definitions. Please update those instead.

2020-09-02 14:26 UTC, wenderjean commented
@kossnocorp The test file hosted in [/src/closestTo/test.js](https://github.com/date-fns/date-fns/blob/master/src/closestTo/test.js) is still relevant? We're discussing about the assertions on lines `36`, `94` and `101` and they look pretty weird actually. Should we take the opportunity to work on them?

1. The assertion in the line `36` could refer itself to a `falsy` value considering the comparison
2. The assertions in the lines `94` and `101` seem to be false positives :thinking: 

What do you think?

2020-09-02 14:28 UTC, V-Gutierrez commented
> @kossnocorp The test file hosted in [/src/closestTo/test.js](https://github.com/date-fns/date-fns/blob/master/src/closestTo/test.js) is still relevant? We're discussing about the assertions on lines `36`, `94` and `101` and they look pretty weird actually. Should we take the opportunity to work on them?
> 
> 1. The assertion in the line `36` could refer itself to a `falsy` value considering the comparison
> 2. The assertions in the lines `94` and `101` seem to be false positives thinking
> 
> What do you think?

That's right, if they still relevant I would gladly update these too !

2020-09-03 07:33 UTC, kossnocorp commented
Yes, please fix the tests as well, much appreciated! 36 def should check for `=== undefined`. Regarding 94 and 101, I'm not sure what to do with it. Do you have any suggestions?

Thank you, guys!

2020-09-03 13:36 UTC, V-Gutierrez commented
> Yes, please fix the tests as well, much appreciated! 36 def should check for `=== undefined`. Regarding 94 and 101, I'm not sure what to do with it. Do you have any suggestions?
> 
> Thank you, guys!

I choose to fix the tests for checking the current behavior of closestTo. Not all cases returns Invalid Date as said in docs but for this issue I believe those fixes will do for now.

2020-09-04 22:32 UTC, hjJunior commented on src/closestTo/test.js
> +  it('returns undefined when undefined is passed as second argument', function() {
```suggestion
  it('returns undefined when the second argument is omitted', function() {
```

2020-09-04 22:32 UTC, hjJunior commented on src/closestTo/test.js
> +  it('converts null into undefined', function() {
```suggestion
  it('returns undefined if the given array is null', function() {
```

2020-09-16 22:47 UTC, ekilah commented
@V-Gutierrez thanks for picking up the issue I created! 🎉

2020-09-24 13:15 UTC, V-Gutierrez commented
@kossnocorp Closing this one since I made further improvements in #1968

2020-09-24 13:15 UTC, closed without merging