Migrate to TS: eachHourOfInterval
date-fns/date-fns pull request #2017
Opened 2020-10-11 17:58 UTC by minitesh

2020-10-12 04:43 UTC, kossnocorp requested changes
Please import `Interval` correctly and remove `only` from tests.

2020-10-12 04:43 UTC, kossnocorp commented on src/eachHourOfInterval/test.ts
> +  it.only('throws an exception if the interval is undefined', () => {
Could you please remove it?

2020-10-12 04:43 UTC, kossnocorp commented on src/eachHourOfInterval/index.ts
> +export default function eachHourOfInterval(dirtyInterval: Interval, options?: {step?: number}): Date[] {
I don't see `Interval` import.

2020-10-12 06:57 UTC, minitesh commented on src/eachHourOfInterval/test.ts
> +  it.only('throws an exception if the interval is undefined', () => {
Yeah sorry my bad.
I realized it later on after I switched off my laptop :(
Will do the changes

2020-10-12 07:23 UTC, minitesh commented on src/eachHourOfInterval/index.ts
> +export default function eachHourOfInterval(dirtyInterval: Interval, options?: {step?: number}): Date[] {
There is no need to import.
There is a definition in `typings.d.ts`
```
type Interval = {
  start: Date | number
  end: Date | number
}
```

2020-10-28 13:02 UTC, kossnocorp commented on src/eachHourOfInterval/index.ts
> +export default function eachHourOfInterval(dirtyInterval: Interval, options?: {step?: number}): Date[] {
The thing is that typings.d.ts is automatically generated and won't be a thing in the future, so we better use explicit imports. No worries, though, I will do it myself in the main branch.

2020-10-28 13:03 UTC, kossnocorp approved these changes
Thanks!

2020-10-28 13:03 UTC, merged

2020-10-29 04:25 UTC, minitesh commented on src/eachHourOfInterval/index.ts
> +export default function eachHourOfInterval(dirtyInterval: Interval, options?: {step?: number}): Date[] {
Ok.
I will take care of this in my next PRs.