fixed issue with Date returning instead of NaN
date-fns/date-fns pull request #2022
Opened 2020-10-13 00:21 UTC by dmarcr1997

Saw there were already tests in place for this issue. I got them to pass by changing the return from new Date(NaN), which returns invalid date, to NaN.

2020-10-27 04:51 UTC, kossnocorp requested changes
Thank you for the change, but I will not merge it right now as it introduces a breaking change. However, it will be handy when I start working on v3. Tests actually check for Invalid Date, which internally represented by NaN, so the PR didn't fix tests 😉

2020-10-27 04:51 UTC, kossnocorp commented on package-lock.json
> +}
Please remove the file from the PR.

2020-10-27 04:51 UTC, kossnocorp commented on src/differenceInBusinessDays/index.js
> +  if (!isValid(dateLeft) || !isValid(dateRight)) return NaN
No need for the comment.

```suggestion
  if (!isValid(dateLeft) || !isValid(dateRight)) return NaN
```

2022-01-30 19:35 UTC, fturmel commented
Going to close this PR if you don't mind. This got fixed and merged when the function was converted to TypeScript (perhaps early by accident), and it's been in v2 releases for a while. See #2012 and #2414

2022-01-30 19:35 UTC, closed without merging