added function - eachMinuteOfInterval
date-fns/date-fns pull request #2032
Opened 2020-10-15 20:58 UTC by vitorfrs-dev

Added the function eachMinuteOfInterval, i did the building process on my machine just like the documentation tells in the Contributing Guide, but the build process have change a bunch of files and the commit would be giant, this is why i commiting only 3 files and not the builded version.

This feature was requested on this issue: #2009

2020-10-16 01:13 UTC, abnersajr requested changes

2020-10-16 01:13 UTC, abnersajr commented on src/eachMinuteOfInterval/index.ts
> + * Return the array of minutes within the specified time interval.
I'm not sure if the description and summary are talking about the same function.

2020-10-16 01:13 UTC, abnersajr commented on src/eachMinuteOfInterval/index.ts
> + * @param {Number} [options.step=1] - the step to increment by. Th starts of hours from the hour of the interval start to the hour of the interval end
I think it's a typo here
```suggestion
 * @param {Number} [options.step=1] - the step to increment by. The starts of hours from the hour of the interval start to the hour of the interval end
```

2020-10-16 01:13 UTC, abnersajr commented on src/eachMinuteOfInterval/index.ts
> + * @throws {RangeError} `options.step` must be a number greater than 1
```suggestion
 * @throws {RangeError} `options.step` must be a number equal or greater than 1
```

2020-10-16 01:13 UTC, abnersajr commented on src/eachMinuteOfInterval/index.ts
> + * @throws {RangeError} Date in interval cannot be `Invalid Dzate`
```suggestion
 * @throws {RangeError} Date in interval cannot be `Invalid Date`
```

2020-10-27 04:21 UTC, kossnocorp commented
> i did the building process on my machine just like the documentation tells in the Contributing Guide, but the build process have change a bunch of files and the commit would be giant, this is why i commiting only 3 files and not the builded version.

Good call, thank you!

2020-10-27 04:22 UTC, kossnocorp commented on src/eachMinuteOfInterval/index.ts
> + * Return the array of minutes within the specified time interval.
In simple functions, they duplicate each other, but often the description contains much more info.

2020-10-27 04:32 UTC, kossnocorp requested changes
The code looks good, thank you a lot! Please address my comments and the PR is ready to go.

2020-10-27 04:32 UTC, kossnocorp commented on src/eachMinuteOfInterval/index.ts
> +}
Please import it from `../types`

2020-10-27 04:32 UTC, kossnocorp commented on src/eachMinuteOfInterval/index.ts
> +}
Please rename it to `StepOptions` and move to `src/types.ts`

2020-10-27 04:32 UTC, kossnocorp commented on src/eachMinuteOfInterval/index.ts
> + *   end: new Date(2014, 9, 6, 15)
```suggestion
 *   start: new Date(2014, 9, 14, 13),
 *   end: new Date(2014, 9, 14, 13, 3)
```

2020-10-27 04:32 UTC, kossnocorp commented on src/eachMinuteOfInterval/index.ts
> +  if(startTime >= endTime) {
While format the file using Prettier.

2020-10-27 12:55 UTC, vitorfrs-dev commented on src/eachMinuteOfInterval/index.ts
> +}
I moved all the interfaces to types.ts

2020-12-15 19:41 UTC, RubenPonce commented
Hey I really like the each day version of the function any chance we could get this one added?

2020-12-15 21:42 UTC, vitorfrs-dev commented
@kossnocorp, I've seen that Travis is failing in the build process, and looks that this problem is happening in other pull requests as well. Do you know what might be causing this problem?

2021-01-19 21:48 UTC, kamranayub commented
> @kossnocorp, I've seen that Travis is failing in the build process, and looks that this problem is happening in other pull requests as well. Do you know what might be causing this problem?

Travis basically shut off for all OSS projects 😞 Have to either request special credits or migrate to new CI. We moved to GitHub Actions ourselves but Circle CI is also an option.

2021-03-24 01:48 UTC, yaseenawazah commented
This is really nice to have, is there something I can do to help get this code merged?

2021-04-08 20:18 UTC, tan75 commented
> This is really nice to have, is there something I can do to help get this code merged?

@yaseenawazah his has been merged via https://github.com/date-fns/date-fns/pull/2382

2021-04-08 20:19 UTC, tan75 commented
hi @vitorfrs-dev,
Thank you for your contribution!
Closing this PR as this has been merged via https://github.com/date-fns/date-fns/pull/2382

2021-04-08 20:19 UTC, closed without merging