Fix Estonian date patterns
date-fns/date-fns pull request #2038
Opened 2020-10-19 01:28 UTC by pgcalixto

Fixes #1571.

2020-10-19 01:30 UTC, pgcalixto commented
I know that ideally every code should have test alongside it, but I could not find tests related to locales :/

If the maintainers need me to write tests on this PR, I could use some help.

2020-10-19 01:40 UTC, pgcalixto commented
The Travis CI is failing, I will later try to found out it. I quickly checked it and it seems to be a snapshot mismatch.

2020-10-27 03:27 UTC, kossnocorp requested changes
Thank you a lot! However, some of the patterns now throw an error. Could you please fix the issue, and I'll merge and ship the PR.

2020-10-27 03:27 UTC, kossnocorp commented on src/locale/et/snapshot.md
> +|                                 |              | 1453-05-29T23:59:59.999Z | pühapäev, 29. mai 1453 kell 23:59:59 GMT+00:00       | Errored                  |
Could you please check why parsing using these patterns throw an error and return `Invalid Date` instead?

2020-10-28 11:40 UTC, pgcalixto commented on src/locale/et/snapshot.md
> +|                                 |              | 1453-05-29T23:59:59.999Z | pühapäev, 29. mai 1453 kell 23:59:59 GMT+00:00       | Errored                  |
I'll take a look into it now!

2020-10-28 13:21 UTC, kossnocorp commented on src/locale/et/snapshot.md
> +|                                 |              | 1453-05-29T23:59:59.999Z | pühapäev, 29. mai 1453 kell 23:59:59 GMT+00:00       | Errored                  |
Appreciate it!

2020-10-28 13:44 UTC, pgcalixto commented on src/locale/et/snapshot.md
> +|                                 |              | 1453-05-29T23:59:59.999Z | pühapäev, 29. mai 1453 kell 23:59:59 GMT+00:00       | Errored                  |
I just fixed 2 of the errors, the ones in PPPP. I'll take a look into the PPPPpppp errors, but I noticed that it is also marked as error in some other locales, even some of the most popular ones:

- https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/snapshot.md
- https://github.com/date-fns/date-fns/blob/master/src/locale/es/snapshot.md
- https://github.com/date-fns/date-fns/blob/master/src/locale/pt-BR/snapshot.md
- https://github.com/date-fns/date-fns/blob/master/src/locale/en-AU/snapshot.md

2020-10-28 13:46 UTC, pgcalixto commented on src/locale/et/snapshot.md
> +|                                 |              | 1453-05-29T23:59:59.999Z | pühapäev, 29. mai 1453 kell 23:59:59 GMT+00:00       | Errored                  |
It seems that it happens because the long time format has a `z`: https://github.com/date-fns/date-fns/blob/44caba8f5950c4ce70b990d1f423105f780841f5/src/locale/et/_lib/formatLong/index.js#L12

And `z` is not a valid key in the parsers object: https://github.com/date-fns/date-fns/blob/44caba8f5950c4ce70b990d1f423105f780841f5/src/parse/_lib/parsers/index.js#L258

2020-10-28 14:29 UTC, pgcalixto commented on src/locale/et/snapshot.md
> +|                                 |              | 1453-05-29T23:59:59.999Z | pühapäev, 29. mai 1453 kell 23:59:59 GMT+00:00       | Errored                  |
@kossnocorp, what do I change 'z' to? 'O', 'OOOO'?

2020-10-28 14:32 UTC, pgcalixto commented on src/locale/et/snapshot.md
> +|                                 |              | 1453-05-29T23:59:59.999Z | pühapäev, 29. mai 1453 kell 23:59:59 GMT+00:00       | Errored                  |
I noticed that the possible keys are:

```js
[
  'G', 'y', 'Y', 'R', 'u', 'Q',
  'q', 'M', 'L', 'w', 'I', 'd',
  'D', 'E', 'e', 'c', 'i', 'a',
  'b', 'B', 'h', 'H', 'K', 'k',
  'm', 's', 'S', 'X', 'x', 't',
  'T'
]
```

`O` is not available 🤔

2021-11-29 21:14 UTC, leshakoss approved these changes
Thanks!

2021-11-29 21:16 UTC, merged