Add next function
date-fns/date-fns pull request #2046
Opened 2020-10-22 00:55 UTC by robtarr

This is in response to https://github.com/date-fns/date-fns/issues/2039. The function signature is a bit different, but it allows for checking for any upcoming day.

2020-10-26 13:17 UTC, robtarr commented
Would it be better to create individual functions for each Day? `nextSaturday`, `nextFriday`, etc.?

2020-10-27 03:06 UTC, kossnocorp commented
Hey, thank you a lot for the function. I like the addition 👍 I would only like to change the name to make it more explicit.

> Would it be better to create individual functions for each day, like nextSaturday, nextFriday, etc.?

We could add it, but that's very specific and niche, not sure so many people will prefer those functions over `next`.

2020-10-27 03:17 UTC, kossnocorp requested changes
Thank you a lot, please address my comments

2020-10-27 03:17 UTC, kossnocorp commented on src/next/index.ts
> +  date: date
Please change the order of the arguments. All the functions have `date` as the first argument.

2020-10-27 03:17 UTC, kossnocorp commented on src/next/index.ts
> +export default function next(
Let's rename the function to `nextDay`. It will make it consistent with other day functions like `getDay` or `setDay`.

2020-10-27 03:17 UTC, kossnocorp commented on src/next/index.ts
> +  return add(date, { days: offset - today })
Please use `addDays` instead as it is more lightweight (as a dependency) than `add`.

2020-10-27 03:17 UTC, kossnocorp commented on src/next/index.ts
> + * @returns {date} the date of the next specified day of the week
Please add JSDoc types ([an example](https://github.com/date-fns/date-fns/blob/master/src/addDays/index.ts#L17-L20)). I know that TSDoc doesn't need those, but we still in transition and need it for generating the docs.

2020-10-27 03:17 UTC, kossnocorp commented on src/next/index.ts
> +  day: number,
Let's make it optional and use `today` if `day` is not passed. I think it covert two use cases:

- Actually set the next day.
- Next given day (Saturday, Friday, etc.).

2020-10-27 13:06 UTC, robtarr commented on src/next/index.ts
> + * @returns {date} the date of the next specified day of the week
I think I fixed this like the example, it looked like it was just the case of the types?

2020-10-27 13:08 UTC, robtarr commented
@kossnocorp, thanks for the feedback. I made some updates. I also renamed `today` as it seemed confusing as it's not actually today. I looked for a convention in the code and didn't see anything.

2021-03-18 21:34 UTC, tan75 commented
Closed via https://github.com/date-fns/date-fns/pull/2214

2021-03-18 21:34 UTC, closed without merging