migrate formatDistance to TS
date-fns/date-fns pull request #2090
Opened 2020-11-16 20:18 UTC by a-korzun

Fixes https://github.com/date-fns/date-fns-typescriptify/issues/32

2021-03-10 21:11 UTC, tan75 requested changes
Please resolve conflicts

2021-03-10 21:20 UTC, tan75 commented
Hello @a-korzun,

could you please resolve conflicts in your code?

2021-03-10 21:21 UTC, tan75 requested changes

2021-03-10 21:21 UTC, tan75 commented on src/formatDistance/test.ts
> -import assert from 'power-assert'
Is there a reason for a this switch from power-assert to assert?

2021-03-11 18:50 UTC, a-korzun commented on src/formatDistance/test.ts
> -import assert from 'power-assert'
Nope. Updated

2021-03-11 18:52 UTC, a-korzun commented
> Hello @a-korzun,
> 
> could you please resolve conflicts in your code?

Hi! Don't see any conflicts, may you provide a bit more information about it?
Just updated PR in order to fix migration from `power-assert`.

2021-03-24 20:09 UTC, tan75 commented
> > Hello @a-korzun,
> > could you please resolve conflicts in your code?
> 
> Hi! Don't see any conflicts, may you provide a bit more information about it?
> Just updated PR in order to fix migration from `power-assert`.

@a-korzun 
It turns out we are using assert now rather than power-assert and you were right when changing it. 
Could you please switch it back? 
Apologies for the confusion!

2021-03-26 16:36 UTC, a-korzun commented
@tan75 Ok, done.

2021-03-26 22:18 UTC, tan75 approved these changes
Thank you for your contribution!

2021-03-29 10:37 UTC, kossnocorp requested changes
Looks good, thanks! Please address my comment about the options type.

2021-03-29 10:37 UTC, kossnocorp commented on src/formatDistance/index.ts
> +export default function formatDistance(dirtyDate: Date | number, dirtyBaseDate: Date | number, dirtyOptions?: Options) {
Please import and use shared types from https://github.com/date-fns/date-fns/blob/master/src/types.ts

```suggestion
export default function formatDistance(dirtyDate: Date | number, dirtyBaseDate: Date | number, options : LocaleOptions & { includeSeconds?: boolean, addSuffix?: boolean } = {}) {
```

I appreciate the effort of exporting the type, but unless it's a common approach in the whole library, we don't want to do it. So please remove the exported type and put the type inline as I suggested. In the future, we might opt to export option types, but we'll need to think about the naming convention first.

2021-03-29 16:25 UTC, a-korzun commented
No problem! Done

2021-04-14 23:40 UTC, tan75 approved these changes
Thank you!

2021-05-05 06:38 UTC, merged