migrate formatDistanceStrict to TS
date-fns/date-fns pull request #2091
Opened 2020-11-16 20:32 UTC by a-korzun

Fixes https://github.com/date-fns/date-fns-typescriptify/issues/33

2021-04-14 22:44 UTC, tan75 commented on src/formatDistanceStrict/index.ts
> +    unit?: 'second' | 'minute' | 'hour' | 'day' | 'month' | 'year',
Could you please move this to [types.ts](https://github.com/date-fns/date-fns/blob/master/src/types.ts) and import it from that file?
see example below:
```
export type Unit =
  | 'year'
  | 'quarter'
  | 'month'
  | 'week'
  | 'day'
  | 'hour'
  | 'minute'
  | 'second'
```

2021-04-14 22:48 UTC, tan75 commented on src/formatDistanceStrict/index.ts
> +    unit?: 'second' | 'minute' | 'hour' | 'day' | 'month' | 'year',
As well, could you please change the remaining `var`s.
Many thanks!

2021-04-14 22:49 UTC, tan75 requested changes
Thanks a lot for this PR!
Please address my comments!

2021-04-15 07:39 UTC, a-korzun commented on src/formatDistanceStrict/index.ts
> +    unit?: 'second' | 'minute' | 'hour' | 'day' | 'month' | 'year',
Yeah, sure! Will do it asap

2021-04-15 19:12 UTC, tan75 approved these changes
Thank you!

2021-05-05 06:36 UTC, merged