[WIP] new locale: Occitan
date-fns/date-fns pull request #2106
Opened 2020-11-26 18:54 UTC by Mejans

Hello!
This is my first PR here. I struggle a bit to end it...
For the "match" part and a JS function called ordinalNumber in Localize.
If someone could give me some hints.

Thanks!

2021-02-20 16:58 UTC, Mejans commented
Hello @kossnocorp @rikkalo may I ask who I can contact to get some help in adding a new locale?
Thanks!

2021-02-21 17:26 UTC, rikkalo commented
Hi, @Mejans!
Thanks for your PR 👍 
You can ask me

2021-02-21 19:55 UTC, Mejans commented
Thanks @rikkalo ,
well I'm not a JavaScript expert, I don't know how to end this PR so it can be added =/

2021-02-22 14:22 UTC, kossnocorp commented
@Mejans please run `yarn build-snapshots` and commit the results. I would also appreciate if you can format the code using Prettier.

2021-04-14 22:26 UTC, tan75 commented
Hi @Mejans 
thank you for this PR! 
The code is failing on the below error - could you please double-check it? 
![image](https://user-images.githubusercontent.com/8555279/114788115-d3347980-9d78-11eb-9898-eb0ef462d9eb.png)

2021-04-14 22:27 UTC, tan75 commented
@Mejans 
as well, please run `yarn locale-snapshots` to update snapshots.

2021-04-14 22:29 UTC, tan75 requested changes
Please address my comments. Let us know if you have any questions!

2021-04-16 15:31 UTC, Mejans commented
> Please address my comments. Let us know if you have any questions!

Hello! Thanks, I've just made some changes, it was thought with PHP on mind, my bad.
I'm not really good at Javascript, I hope this passes the test!

2021-10-17 08:52 UTC, tan75 commented
Hi @Mejans 
apologies for the delay - the tests are failing because this locale is missing the below file:
`_lib/match/index.js`

The instructions on how to create this file are below:
https://date-fns.org/v2.25.0/docs/I18n-Contribution-Guide#match

Could you please have a look into this again?

2021-11-23 22:27 UTC, tan75 commented
TODO: delete the branch https://github.com/date-fns/date-fns/pull/2698

2022-01-05 17:51 UTC, fturmel commented
Hope that's OK, trying to help push this to the finish line.

- rebased onto current master
- converted to TypeScript
- created the `match` file as best as I could by referencing the work in `localize`. I don't speak the language but do speak French, so it wasn't too hard to track progress

@Mejans Can you review the work and the snapshot.md file, and let us know how it looks?

2022-01-05 17:57 UTC, Mejans commented
@fturmel d'accord :) Merci beaucoup, je vais regarder les fichiers pour vous dire si ça me semble bon. Encore merci

2022-01-05 17:58 UTC, Mejans commented on src/locale/oc/_lib/formatDistance/index.ts
> +    one: 'gaireben an',
missing "un" between gaireben and an.

2022-01-05 18:06 UTC, Mejans commented on src/locale/oc/snapshot.md
> +| 1998-12-01T00:00:00.000Z | 1 an        | fa 1 an            | 9504 oras                      |
hum, maybe "1 e mièg" if possible or "1,5 an"

2022-01-05 18:07 UTC, Mejans commented on src/locale/oc/snapshot.md
> +| 2001-06-01T00:00:00.000Z | 1 an        | d’aquí 1 an        | 12408 oras                     |
if possible "1,5 ans" in place of "1 an"

2022-01-05 18:13 UTC, fturmel commented on src/locale/oc/_lib/formatDistance/index.ts
> +    one: 'gaireben an',
Made the correction

2022-01-05 18:15 UTC, Mejans commented on src/locale/oc/snapshot.md
> +| Calendar year                   | yo           | 1987-02-11T12:13:14.015Z | 1987ena                                           | 1987-01-01T00:00:00.000Z |
if the excepted output was the year, then it's not correct. Should only be "1987", it was excepted to be "the 1987th year", then it's correct

2022-01-05 18:15 UTC, fturmel commented on src/locale/oc/snapshot.md
> +| 2001-06-01T00:00:00.000Z | 1 an        | d’aquí 1 an        | 12408 oras                     |
Don't think that's possible, the function truncates to the largest unit.

2022-01-05 18:18 UTC, fturmel commented
@Mejans It might help if you compare to the more thoroughly tested outputs of the [en-US](https://github.com/date-fns/date-fns/blob/master/src/locale/en-US/snapshot.md) or [fr](https://github.com/date-fns/date-fns/blob/master/src/locale/fr/snapshot.md) locales

2022-01-05 18:20 UTC, Mejans commented
sure ah ah ah, will avoid questioning ah ah.
Can I do it for tomorrow?

2022-01-05 18:23 UTC, fturmel commented on src/locale/oc/snapshot.md
> +| 1999-12-27T00:00:00.000Z | lo diluns passat a 12946252800000 |
> lo diluns passat a 12946252800000

Definitely something off here. It's coming from `formatRelative` last week format: `'lo' eeee 'passat a' LT`

Let me know what the correct value should be and I'll update it.

2022-01-05 18:26 UTC, fturmel commented on src/locale/oc/snapshot.md
> +| 1999-12-27T00:00:00.000Z | lo diluns passat a 12946252800000 |
In French, it's: `eeee 'dernier à' p,`, I suppose we just need to change `LT` to `p`. Let me just do that for now.

2022-01-05 18:31 UTC, fturmel commented
> Can I do it for tomorrow?

Of course, no rush. This PR was dormant for over a year. I'm just stepping in to help a bit.

Ce serait dommage de perdre tout ce travail!

2022-01-05 18:33 UTC, fturmel commented on src/locale/oc/snapshot.md
> +|                                 | PPPppp       | 1987-02-11T12:13:14.015Z | 11 de febrièr 1987 a 12:13:14 GMT+0               | Errored                  |
We can ignore this, it's a larger issue either with snapshot generation or a limitation of the parser. I think most (if not all) locales error out here. Something to look at eventually.

2022-01-05 18:36 UTC, fturmel commented on src/locale/oc/snapshot.md
> +| Calendar year                   | yo           | 1987-02-11T12:13:14.015Z | 1987ena                                           | 1987-01-01T00:00:00.000Z |
Yes, `yo` is calendar year ordinal, so it does mean 1987th.

2022-01-05 18:43 UTC, Mejans commented
Merci de l'avoir réveillé surtout ! Ça me faisait un peu de peine de savoir que j'avais une PR en attente, mais je ne savais pas par quoi commencer. 1 000 mercis

2022-01-06 16:45 UTC, Mejans commented on src/locale/oc/_lib/formatRelative/index.ts
> +  lastWeek: "'lo' eeee 'passat a' p",
remove the 'lo' here

2022-01-06 16:45 UTC, Mejans commented on src/locale/oc/_lib/localize/index.ts
> +  narrow: ['1', '2', '3', '4'] as const,
almost like in French better:
  narrow: ['T1', 'T2', 'T3', 'T4'] as const,
  abbreviated: ['1èr trim.', '2nd trim.', '3en trim.', '4en trim.'] as const,

2022-01-06 16:47 UTC, Mejans commented on src/locale/oc/_lib/formatLong/index.ts
> +  full: "EEEE, d 'de' MMMM y",
remove the "," after EEEE, like in French

2022-01-06 16:47 UTC, Mejans commented
Done!

2022-01-06 17:46 UTC, fturmel commented
Thanks for reviewing all this, last changes were made. Seems like we're good to go?

2022-01-06 17:47 UTC, fturmel approved these changes

2022-01-06 17:59 UTC, Mejans commented
Yes, brilliant, many thanks!

2022-01-10 13:41 UTC, merged