Add intlFormat function
date-fns/date-fns pull request #2172
Opened 2021-01-23 00:00 UTC by rikkalo

- Add intlFormat with Intl.DateTimeFormat
- Add tests for intlFormat

2021-01-25 12:22 UTC, kossnocorp requested changes
Like the code, simple and straightforward, please remove the runtime check and add docs.

2021-01-25 12:22 UTC, kossnocorp commented on src/intlFormat/index.ts
> +    localeOptions = formatOrLocale
Let's not assert this. I know that the rest of the library does similar checks, but in v3 I want to remove runtime checks and make users rely on the type systems. This will make the library leaner and faster.

2021-01-25 16:52 UTC, kossnocorp commented on src/intlFormat/index.ts
> -  requiredArgs(1, arguments)
Whoops, please keep this one though. We'll remove them in v3.

2021-01-25 16:53 UTC, rikkalo commented on src/intlFormat/index.ts
> -  requiredArgs(1, arguments)
Soooorry, I will fix

2021-02-03 03:37 UTC, kossnocorp approved these changes
With a minor change, I think it's ready.

2021-02-03 03:37 UTC, kossnocorp commented on src/intlFormat/index.ts
> +) {
Let's force return type at all times.

```suggestion
): string {
```

2021-02-09 03:34 UTC, merged

2021-02-23 00:27 UTC, codecog commented
This commit has introduced failing tests. Specifically the way it formats dates and time offset.

1. https://github.com/date-fns/date-fns/pull/2172/commits/02ff9ffb126c34701ab467e60e813751cf3b6584#diff-290f33a437a36a2c9c63d837b9c054f73e830b317f883bcfd4455259ceffa8b0R9-R15
2. https://github.com/date-fns/date-fns/pull/2172/commits/02ff9ffb126c34701ab467e60e813751cf3b6584#diff-290f33a437a36a2c9c63d837b9c054f73e830b317f883bcfd4455259ceffa8b0R17-R33

2021-02-23 11:39 UTC, rikkalo commented
> This commit has introduced failing tests. Specifically the way it formats dates and time offset.
> 
> 1. [02ff9ff#diff-290f33a437a36a2c9c63d837b9c054f73e830b317f883bcfd4455259ceffa8b0R9-R15](https://github.com/date-fns/date-fns/commit/02ff9ffb126c34701ab467e60e813751cf3b6584#diff-290f33a437a36a2c9c63d837b9c054f73e830b317f883bcfd4455259ceffa8b0R9-R15)
> 2. [02ff9ff#diff-290f33a437a36a2c9c63d837b9c054f73e830b317f883bcfd4455259ceffa8b0R17-R33](https://github.com/date-fns/date-fns/commit/02ff9ffb126c34701ab467e60e813751cf3b6584#diff-290f33a437a36a2c9c63d837b9c054f73e830b317f883bcfd4455259ceffa8b0R17-R33)

This PR fixes this problem.
https://github.com/date-fns/date-fns/pull/2232