Intl format relative2
date-fns/date-fns pull request #2173
Opened 2021-01-24 22:26 UTC by tan75

2021-01-25 16:39 UTC, kossnocorp requested changes
Great job, code and tests look good.

Besides review comments I have few requests:

- Please rewrite it to TypeScript. If you never worked with it or just need advice - ping me, I'll help you.

- Let's change the behavior. You can see that our `formatDistance` picks the most appropriate unit depending on the distance. The less the distance the smaller the unit. Let emulate this algo but allow users pass `unit` as well. So that we can move `unit` to options and make it optional.
  
  Here's the algo I suggest (tell me if you have other ideas)

  - Less than minites: `second`
  - Less than hour: `minute`
  - Less than day: `hour`
  - Less than week: `day`
  - Less than quarter: `month`
  - Less than year: `quarter`
  - More or equal to year: `year`

- Let's rename the function to `intlFormatDistance` and make API similar to https://date-fns.org/v2.16.1/docs/formatDistance. Initially, I wanted to keep it similar to Intl API, but realized that it will confuse **our** users.

- Add a second date argument like in `formatDistance` and use it in calculations instead of `new Date()`.

-  Add another function variation `intlFormatDistanceToNow` similar to https://date-fns.org/v2.16.1/docs/formatDistanceToNow that uses Date.now() as the second argument.

2021-01-25 16:39 UTC, kossnocorp commented on src/intlFormatRelative/index.js
> +export default function intlFormatRelative(date, unit, locale, options) {
Let's make `locale` an options field.

2021-01-25 16:39 UTC, kossnocorp commented on src/intlFormatRelative/index.js
> +  } else if (unit === units[14] || unit === units[15]) {
These conditions are hard to read. Let's simplify and use a single unit. Right now, we have `formatDistanceStrict` that uses 'second', let's stick to it.

Also, since we don't need to check unit argument for validity (see my comments above and below), we can just write 

```
} else if (unit === 'second') {
```

2021-01-25 16:39 UTC, kossnocorp commented on src/intlFormatRelative/index.js
> +  return rtf.format(value, unit)
Regarding what to do when `unit` argument is not valid.

If unit is undefined, JS throws this error:

```js
(new Intl.RelativeTimeFormat()).format(0)
//=> VM267:1 Uncaught RangeError: Invalid unit argument for Intl.RelativeTimeFormat.prototype.format() 'undefined'
//=>    at RelativeTimeFormat.format (<anonymous>)
//=>    at <anonymous>:1:33(new Intl.RelativeTimeFormat()).format(0)
```

It's not super clear but not terrible either. Our stance - users should use type systems (TypeScript or Flow) for type checks. Our focus is small build size, and excluding type checks code is an easy way to ensure it.

I hope you get my point. You can ping me for more details.

2021-01-25 16:39 UTC, kossnocorp commented on src/intlFormatRelative/test.js
> +it('should return 1 year ago', function () {
Please wrap all tests in `describe('intlFormatDistance', () => {`

2021-01-25 16:39 UTC, kossnocorp commented on src/intlFormatRelative/test.js
> +})
After adding the second argument, please add cases for `in 1 second`, `in 1 week`, etc.

2021-01-28 15:46 UTC, tan75 commented on src/intlFormatRelative/index.js
> + */
Addressed as below:
* @example
 * // What is the distance between Mar, 4 1986 11:30:00 and Mar, 4 1986 10:30:00 in Intl?
 * const result = intlFormatDistance(
 *   new Date(1986, 3, 4, 11, 30, 0),
 *   new Date(1986, 3, 4, 10, 30, 0));
 * // => in 1 hour
 *

2021-01-28 15:46 UTC, tan75 commented on src/intlFormatRelative/index.js
> + * @param {Object} [options={}] - optional object with the following properties:
Addressed as below: 

`@param {String|String[]} [rtfOptions.locales='en'] - a string (or array of strings) with a BCP 47 language tag. `

2021-01-28 15:47 UTC, tan75 commented on src/intlFormatRelative/index.js
> +    throw new Error('Invalid unit supplied')
Addressed.

2021-01-28 15:47 UTC, tan75 commented on src/intlFormatRelative/index.js
> +export default function intlFormatRelative(date, unit, locale, options) {
Addressed.

2021-01-28 15:47 UTC, tan75 commented on src/intlFormatRelative/index.js
> +  } else if (unit === units[14] || unit === units[15]) {
Addressed.

2021-01-28 15:47 UTC, tan75 commented on src/intlFormatRelative/index.js
> +  return rtf.format(value, unit)
Addressed.

2021-01-28 15:48 UTC, tan75 commented on src/intlFormatRelative/test.js
> +it('should return 1 year ago', function () {
Addressed.

2021-01-28 15:48 UTC, tan75 commented on src/intlFormatRelative/test.js
> +})
Addressed.

2021-01-28 15:48 UTC, tan75 commented
WIP:
* intlFormatDistanceToNow
* Test Cases

2021-02-01 13:44 UTC, kossnocorp requested changes
Good progress. Please format the code using Prettier and address my suggestions.

2021-02-01 13:44 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> +const SECONDS_IN_YEAR = 31104000; // 12 months in year
Regrading these. Let use the same approach I used in the milliseconds function: https://github.com/date-fns/date-fns/blob/master/src/milliseconds/index.ts#L6

You can move the constant to the shared module and reuse it from there: https://github.com/date-fns/date-fns/blob/master/src/constants/index.js

2021-02-01 13:44 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * | new Date(1986, 3, 4, 10, 30, 0)                              |               |
Let's repurpose this table instead: https://github.com/date-fns/date-fns/blob/master/src/formatDistance/index.js#L23-L40

2021-02-01 13:44 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + *   { unit: 'minute', locales: 'es' });
Please format examples (and code btw) using Prettier. If you use VS Code, I would recommend making it to format the code on save.

2021-02-01 13:44 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * @param {String} [rtfOptions.unit=''] - values "year", "quarter", "month", "week", "day", "hour", "minute", "second" as per MDN Web Docs.
```suggestion
 * @param {String} [rtfOptions.unit] - formats the distance with the given unit ("year", "quarter", "month", "week", "day", "hour", "minute", "second").
```

2021-02-01 13:44 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#locale_identification_and_negotiation
```suggestion
 * @param {String|String[]} [rtfOptions.locales] - the locale to use (BCP 47 language tag). [For the reference see MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#locale_identification_and_negotiation).
```

2021-02-01 13:44 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * @param {String} [rtfOptions.options.style='long'] - the length of the internationalized message. Other values: "short" or "narrow";
Let's make the options object flat and move all properties to rtfOptions (and rename it simply options).

2021-02-01 13:44 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/RelativeTimeFormat
Instead of forcing users to read MDN, we can add either example for each option variant or a table to the description.

2021-02-01 13:44 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> +}
Please upgrade typescript to the latest (4.1.3) and add `ESNext.Intl` to https://github.com/date-fns/date-fns/blob/master/tsconfig.json#L4

```suggestion
interface Options {
  localeMatcher?: Intl.RelativeTimeFormatLocaleMatcher,
  numeric?: Intl.RelativeTimeFormatNumeric,
  style?: Intl.RelativeTimeFormatStyle,
  unit?: Unit,
  locale?: Intl.RelativeTimeFormatStyle
}
```

Note that I renamed `locales` -> `locale` as I think a single locale will be used the most, so better make it look good for the default case.

Then add `Unit` to https://github.com/date-fns/date-fns/blob/master/src/types.ts:

```ts
export type Unit =
  | 'year'
  | 'quarter'
  | 'month'
  | 'week'
  | 'day'
  | 'hour'
  | 'minute'
  | 'second'
```

There's `RelativeTimeFormatUnit` but I prefer limit options (it's easy to extend than limit later) and use the same type in other functions.

2021-02-01 13:44 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> +    rtfOptions?.options || {}
Now I understand why you did make nested `options`, but let's instead explicitly specify the options here.

2021-02-01 13:44 UTC, kossnocorp commented on src/intlFormatDistance/test.ts
> +describe('intlFormatDistance edge cases', () => {
Add this as a nested descript to `describe('intlFormatDistance',`.  We follow a rule: "one root-level `describe` per file".

2021-02-06 20:06 UTC, tan75 commented on src/intlFormatDistance/index.ts
> + * | new Date(1986, 3, 4, 10, 30, 0)                              |               |
I will still have to modify the table because we've got units passed in as well. E.g. a value of 60 seconds can be represented by either **'in 60 seconds'** or **'in 1 minute'** result
Do I need to create examples that will satisfy every unit?

2021-02-06 20:07 UTC, tan75 commented on src/intlFormatDistance/index.ts
> + *   { unit: 'minute', locales: 'es' });
Done

2021-02-06 22:28 UTC, tan75 commented on src/intlFormatDistance/index.ts
> + * @param {String} [rtfOptions.options.style='long'] - the length of the internationalized message. Other values: "short" or "narrow";
Done as below:
```
type Options = {
  unit?: String
  locales?: String
  localeMatcher?: String
  numeric?: String
  style?: String
}

export default function intlFormatDistance(
  date: Date | number,
  baseDate: Date | number,
  options?: Options
)
```

2021-02-06 22:31 UTC, tan75 commented on src/intlFormatDistance/index.ts
> +    rtfOptions?.options || {}
Will this suffice?
```
  const rtf = new Intl.RelativeTimeFormat(
    options?.locale || defaultLocale,
    {
      localeMatcher: options?.localeMatcher,
      numeric: options?.numeric,
      style: options?.style,
    } || {}
  )

```

2021-02-07 20:32 UTC, tan75 commented on src/intlFormatDistance/test.ts
> +describe('intlFormatDistance edge cases', () => {
Done

2021-02-07 21:05 UTC, tan75 commented on src/intlFormatDistance/index.ts
> +const SECONDS_IN_YEAR = 31104000; // 12 months in year
@kossnocorp please check my approach in my latest commit and let me know

2021-02-07 21:06 UTC, tan75 commented on src/intlFormatDistance/index.ts
> + * | new Date(1986, 3, 4, 10, 30, 0)                              |               |
@kossnocorp 
WIP

2021-02-07 21:06 UTC, tan75 commented on src/intlFormatDistance/index.ts
> + * @param {String} [rtfOptions.unit=''] - values "year", "quarter", "month", "week", "day", "hour", "minute", "second" as per MDN Web Docs.
done

2021-02-07 21:09 UTC, tan75 commented on src/intlFormatDistance/index.ts
> + * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/RelativeTimeFormat
WIP

2021-02-07 21:21 UTC, tan75 commented on src/intlFormatDistance/index.ts
> +}
@kossnocorp 
the only thing i decided to change was the order or the properties (unit goes first) to follow the order in the MDN documentation (if thats ok). I think this makes more sense :

```
interface Options {
  unit?: Unit
  locale?: Intl.RelativeTimeFormatStyle
  localeMatcher?: Intl.RelativeTimeFormatLocaleMatcher
  numeric?: Intl.RelativeTimeFormatNumeric
  style?: Intl.RelativeTimeFormatStyle
}


```

2021-02-08 19:52 UTC, leshakoss commented on src/constants/index.ts
> +export let yearInDays: number = 365.2425
Shouldn't it be the other way around, `daysInYear`, as in [number of] days in [a] year?

2021-02-08 20:00 UTC, tan75 commented on src/constants/index.ts
> +export let yearInDays: number = 365.2425
> Shouldn't it be the other way around, `daysInYear`, as in [number of] days in [a] year?

it totally makes sense but i took it from here:
https://github.com/date-fns/date-fns/blob/master/src/milliseconds/index.ts#L6

2021-02-08 20:03 UTC, tan75 commented on src/constants/index.ts
> +export let yearInDays: number = 365.2425
> Shouldn't it be the other way around, `daysInYear`, as in [number of] days in [a] year?

yeah, i think I will change it - your way is more explicit

2021-02-09 03:30 UTC, kossnocorp commented on src/constants/index.ts
> +export let yearInDays: number = 365.2425
👍

2021-02-24 12:26 UTC, robertvanhoesel commented
Awesome work! While working on my own implementation I found a a gotcha with `numeric: 'auto'` which might be wise to address (or at least mention in documentation). Because `RelativeTimeFormat` only takes a value and unit, it has no context/awareness of years. 

When I compare two dates, today (Feb 24, 2020) and almost 2 years ago (March 30, 2019).`dateFns.differenceInYears` will return '-1', which is correct, it is not 2 years ago, just one and a bit. 

```ts
new Intl.RelativeTimeFormat('en', { 
  numeric: "auto" 
}).format(-1, 'year')
// 'last year'
```

The majority of Intl implementations will return `last year` in response to above code, which to humans is just incorrect when we are aware of comparing 2021 and 2019, which was not 'last year'. 

https://codesandbox.io/s/musing-river-90m6t?file=/src/index.ts

Since your proposed implementation always takes two dates, you could prevent this error from occurring by having additional checks in the [unit resolver](https://github.com/date-fns/date-fns/pull/2173/files#diff-85e3d08d9b516732ef39e93d178a81815de328e6929a6e218282166c1ab42556R237-R249) that only applies 'auto' when the two compared years differ exactly 1 year, and force 'numeric' in all other cases. 

@kossnocorp It occurs to me that maybe this more opinionated/smart logic should be in `Intl.RelativeTimeFormat` instead? Alongside rounding instead of flooring (i.e. 1 year 9 months becomes 2 years) and optional joining in localized time?

2021-02-24 12:36 UTC, robertvanhoesel commented
Or... split this implementation to:
- `intlFormatDistanceStrict` which uses `numeric: always` and takes 'ceil', 'round', 'floor' arguments.
-  `intlFormatDistance` which uses `numeric: auto` where applicable and generally rounds the years.

My 2cts would be to avoid providing the exact arguments of `Intl.RelativeTimeFormat` and allow room to algorithmically use the right unit and formatting options.

An other thing to review would be wether outputting 'quarters' by default makes sense to most implementations. Date-fns is slightly opinionated in its other implementations (i.e. when to include time in 'relative' and never returning '4 quarters ago' in formatDistance), providing that as an option to control would make this more useful, otherwise I would find myself going back to first comparing the dates, then calling intlFormatDistance with unit months when I know we're talking about 3-12 months distance.

2021-02-24 12:40 UTC, robertvanhoesel commented on src/intlFormatDistance/index.ts
> +  let unit
```suggestion
  let value: number
  let unit: Intl.RelativeTimeFormatUnit
```

2021-03-05 02:24 UTC, kossnocorp requested changes
Some more new comments

2021-03-05 02:24 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + *   { unit: 'minute', locales: 'de' });
```suggestion
 *   { unit: 'minute', locale: 'de' });
```

2021-03-05 02:24 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + *   { unit: 'minute', locales: 'es' });
```suggestion
 *   { unit: 'minute', locale: 'es' });
```

2021-03-05 02:24 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + *   { unit: 'minute', locales: 'es' });
I can see that examples are still not formatted, for instance here the final `)` must be on a new page and the semicolon should be committed. Please check other examples as well.

2021-03-05 02:24 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * // => in 1 hour
Please here and below 1) make output consistent (always has `=>`, no space between it and the comment) and 2) wrap strings into quotes.

```suggestion
 * //=> 'in 1 hour'
```

2021-03-05 02:59 UTC, kossnocorp commented
@robertvanhoesel, this is an excellent point. Adding special logic for `numeric: 'auto'` and `-1`/`1`/`0` makes sense at first glance, not only for `year` but also `month` and `quarter`. However, I'm afraid it's a slippery slope. For instance, this is not a problem for `minute` and `hour` in English, but I imagine it might be a case for other languages or Intl implementations or wise versa might not have an issue with `year`.

Using `ceil`/`floor` won't help because rounding `4 months` to `0 years` while working with December will produce `this year` and its inaccuracy.

I think instead we can use `differenceInCalendarDays`, `differenceInCalendarWeeks`, `differenceInCalendarMonths` and `differenceInCalendarYears` **unless** `numeric` is set to `always`. Then with your example, you'll get `-2 "2 years ago"`.

We also should make `numeric: 'auto'` the default value because such:

```ts
new Intl.RelativeTimeFormat('en').format(0, 'year')
//=> "in 0 years"
```

..it is not a good default option. However, I'm not sure what are side effects of this change. @tan75 could you please explore that?

@robertvanhoesel @tan75 @leshakoss @rikkalo WDYT?

2021-03-17 21:26 UTC, tan75 commented
@kossnocorp 
If `numeric: auto` is a default option, then when adding `style: short` it falls back to `numeric: always` (if the result is 1 day or 1 month or 1 year) e.g.:
```
const result = intlFormatDistance(
      new Date(1985, 4, 5, 10, 30, 0),
      new Date(1985, 4, 4, 10, 30, 0),
      { style: 'short' }
) //=> 'in 1 day' instead of 'tomorrow'
```

however it looks like explicitly adding `numeric: auto`  when calling the function will fix it (even though we know that's the case by default):

```
    const result = intlFormatDistance(
      new Date(1985, 4, 5, 10, 30, 0),
      new Date(1985, 4, 4, 10, 30, 0),
      { style: 'short', numeric: 'auto' }
   )//=> 'tomorrow'
```

The same happens to 1 month and 1 year

2021-04-17 21:13 UTC, tan75 commented
hi @robertvanhoesel 
my tests are failing on this [Error](https://github.com/date-fns/date-fns/pull/2173/checks?check_run_id=2371282512#step:8:2108)

![image](https://user-images.githubusercontent.com/8555279/115126770-90b5ab80-9fc9-11eb-8edd-f2b912c04785.png)

Any ideas why?

2021-04-17 21:42 UTC, robertvanhoesel commented
@tan75 the typescript compiler needs to know that you are using es2020.intl definitions. In .tsconfig you should add es2020 to the target. Also, this is a good case to catch, as older browser will also not know about this constructor and fail.

2021-04-17 21:48 UTC, robertvanhoesel commented
I use the below logic to check wether the API is available in the browser. 
```
const IntlRelativeSupported = typeof Intl.RelativeTimeFormat === 'function';
```

2021-04-18 10:20 UTC, tan75 commented
> @tan75 the typescript compiler needs to know that you are using es2020.intl definitions. In .tsconfig you should add es2020 to the target. Also, this is a good case to catch, as older browser will also not know about this constructor and fail.

Thank a lot for your answer! Do you mean tsconfig.json? I added it here 
[tsconfig](https://github.com/date-fns/date-fns/pull/2173/files#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0R3-R4)
But is it still failing:
[Run](https://github.com/date-fns/date-fns/pull/2173/checks?check_run_id=2373675432#step:8:1950)

2021-11-30 15:29 UTC, leshakoss approved these changes
⭐️

2021-12-02 03:15 UTC, kossnocorp requested changes

2021-12-02 03:15 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> +  let dateRight = toDate(baseDate)
```suggestion
  const dateLeft = toDate(date)
  const dateRight = toDate(baseDate)
```

2022-02-08 04:13 UTC, kossnocorp requested changes
I believe that the implementation is perfect, but it's distracting because both documentation and tests aren't descriptive, and I have a hard time parsing it. I imagine users will have trouble too.

2022-02-08 04:13 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * // What is the distance between Apr, 4 1986 11:30:00 and Apr, 4 1986 10:30:00 in Intl?
Please make sure that the examples say exactly what you trying to show instead of repeating what it does: https://www.loom.com/share/516194288d764b5b8fc233c5de47b10a

Also, please reduce the number of examples to the required minimum.

2022-02-08 04:13 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * |    Distance between dates   |               Result               |
Please rework the doc tables: https://www.loom.com/share/ede734c88e1c4943b095e6b17d387f83

2022-03-13 23:13 UTC, tan75 commented
Current test structure:
![image](https://user-images.githubusercontent.com/8555279/158083362-c90720fa-1a0a-499d-9bc7-d9adf21753cf.png)

2022-03-15 03:46 UTC, tan75 commented on src/intlFormatDistance/index.ts
> + * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/RelativeTimeFormat
is this ok ? 
`e.g. "hi": Hindi (language) or "de-AT": German (language) as used in Austria (region)`

2022-03-15 04:36 UTC, kossnocorp approved these changes

2022-03-15 04:36 UTC, kossnocorp commented on src/constants/index.ts
> +export let daysInYear: number = 365.2425
```suggestion
export const daysInYear: number = 365.2425
```

2022-03-15 04:36 UTC, kossnocorp commented on src/constants/index.ts
> + *  @constant
```suggestion
 *
 * @name secondsInDay
 * @constant
```

2022-03-15 04:36 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * |    Distance between dates   |               Result               |
I meant to change the table to express what they get:

```
0 seconds | now
1-59 seconds | in X seconds
1-59 minutes | in X minutes
```

2022-03-15 04:36 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * or allows a user to pass in a unit as well.
```suggestion
 * or allows the user to specify the unit as well.
```

2022-03-15 04:36 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * If a unit is passed in, it will be applied accordingly. Otherwise - see the table below:
```suggestion
 * If the unit is specified, it will be applied accordingly. Otherwise - see the table below:
```

2022-03-15 04:36 UTC, kossnocorp commented on src/intlFormatDistance/test.ts
> +
```suggestion
```

2022-03-15 04:36 UTC, kossnocorp commented on src/intlFormatDistance/test.ts
> +    it('checks numerick', () => {
```suggestion
    it('checks numeric', () => {
```

2022-06-10 05:34 UTC, kossnocorp requested changes

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> +} from '../constants'
```suggestion
} from '../constants/index'
```

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> +import { IntlOptionsUnit } from 'src/types'
```suggestion
import type { IntlOptionsUnit } from '../types'
```

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> +interface Options {
```suggestion
export interface IntlFormatDistanceOptions {
```

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * If the unit is specified, it will be applied accordingly. Otherwise - see the table below:
```suggestion
 * The function calculates the difference between two dates and formats it as a human-readable string.
 *
 * The function will pick the most appropriate unit depending on the distance between dates. For example, if the distance is a few hours, it might return `x hours`. If the distance is a few months, it might return `x months`.
 *
 * You can also specify a unit to force using it regardless of the distance to get a result like `123456 hours`.
 *
 * See the table below for the unit picking logic:
```

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * |  X years ago                | X years ago            |
```suggestion
 * | Distance between dates | Result (past)  | Result (future) |
 * | ---------------------- | -------------- | --------------- |
 * | 0 seconds              | now            | now             |
 * | 1-59 seconds           | X seconds ago  | in X seconds    |
 * | 1-59 minutes           | X minutes ago  | in X minutes    |
 * | 1-23 hours             | X hours ago    | in X hours      |
 * | 1 day                  | yesterday      | tomorrow        |
 * | 2-6 days               | X days ago     | in X days       |
 * | 7 days                 | last week      | next week       |
 * | 8 days-1 month         | X weeks ago    | in X weeks      |
 * | 1 month                | last month     | next month      |
 * | 2-3 months             | X months ago   | in X months     |
 * | 1 quarter              | last quarter   | next quarter    |
 * | 2-3 quarters           | X quarters ago | in X quarters   |
 * | 1 year                 | last year      | next year       |
 * | 2+ years               | X years ago    | in X years      |
```

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * //=> 'in 4 quarters'
Please make the result `5 quarters` to illustrate the point

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * // The option represents the unit which will be used for the result calculation.
Please put the option name upfront

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * //=> 'dentro de 60 minutos'
Please make the example locale focused to avoid confusion, and also don't forget to update the comment.

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * // What is the distance in Spanish in minutes between the dates when the fist date is after the second?
```suggestion
```

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * // What is the distance in quarters between the dates when the fist date is after the second?
```suggestion
```

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * // What is the distance in numeric format between the dates when the fist date is after the second?
```suggestion
```

2022-06-10 05:34 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + * // The option represents the numeric format which will be used for the result representation.
Please use this example to update the option examples comment above and below:

```suggestion
 * // Use the numeric option to force the function to use numeric values. Without setting it, the example would return "tomorrow". 
```

2022-06-13 05:17 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> + *
```suggestion
```

2022-06-13 05:18 UTC, kossnocorp commented on src/intlFormatDistance/index.ts
> +
```suggestion
```

2022-06-13 05:21 UTC, kossnocorp approved these changes
👏

2022-06-13 05:53 UTC, merged

2022-09-29 19:22 UTC, orhangazi commented
Hi, I can't pass this [error](https://github.com/date-fns/date-fns/pull/2173#issuecomment-821888470). I am using react native version is 0.68.2, react version is 17.0.2 and using date-fns version is 2.29.3.  Code reference doc [here](https://date-fns.org/v2.29.3/docs/intlFormatDistance#examples).
```
lastMessageDeliveryDate = intlFormatDistance(
			new Date(1986, 3, 4, 11, 30, 0),
			new Date(1986, 3, 4, 10, 30, 0)
		)
```
I am getting this error:
![image](https://user-images.githubusercontent.com/2978281/193122747-aa45b2f3-3370-4d13-9d22-9e5bfc343ae4.png)

2022-11-09 13:39 UTC, hrdyjan1 commented on src/intlFormatDistance/index.ts
> + * // What is the distance between the dates when the fist date is after the second?
Typo - first

2023-05-16 08:42 UTC, JestemTrzcinska commented
Hi, I also encountered [this](https://github.com/date-fns/date-fns/pull/2173#issuecomment-821888470) problem. The same result as [here](https://github.com/date-fns/date-fns/pull/2173#issuecomment-1262715438).
It works good on newer iOS simulators, but it doesn't on Android simulators and old iPhone simulators like iPhone 6s with iOS 13.7. 

Any workaround? I need something exactly like intlFormatDistance with its "... ago" etc. 

Making if statement is not good way for me, because I need it to work on every devices.

```
"date-fns": "^2.29.3",
"react": "18.2.0",
"react-native": "0.71.6",
```