Add next mon tue
date-fns/date-fns pull request #2214
Opened 2021-02-19 22:17 UTC by tan75

Add nextTuesday() with minor changes

2021-02-22 13:58 UTC, kossnocorp requested changes
The logic is great, but I would simplify it a bit for build size sake. I suggest applying the same approach as in `nextMonday` everywhere.

2021-02-22 13:58 UTC, kossnocorp commented on src/nextMonday/index.ts
> +  }
```suggestion
  return addDays(date, map[getDay(date)])
```

2021-02-22 13:58 UTC, kossnocorp commented on src/nextMonday/index.ts
> +/**
```suggestion

const map = [1, 7, 6, 5, 4, 3, 2]

/**
```

2021-02-24 05:35 UTC, kossnocorp requested changes

2021-02-24 05:35 UTC, kossnocorp commented on src/nextDay/index.ts
> +export default function nextDay(date: Date, day: number): Date {
```suggestion
export default function nextDay(date: Date | number, day: number): Date {
```

2021-02-24 05:35 UTC, kossnocorp commented on src/nextDay/index.ts
> + * @param {Date} date - the date to check
```suggestion
 * @param {Date | number} date - the date to check
```

2021-02-24 05:35 UTC, kossnocorp commented on src/nextDay/index.ts
> + * {0|1|2|3|4|5|6} the day of week, 0 represents Sunday
```suggestion
 * When is the next day of the week? 0-6 the day of the week, 0 represents Sunday.
```

2021-02-24 05:35 UTC, kossnocorp commented on src/nextDay/index.ts
> + * => new Date(2020, 2, 24)
Please update the examples

2021-02-24 15:46 UTC, tan75 commented on src/nextDay/index.ts
> + * => new Date(2020, 2, 24)
Updated as below:

```
 * @example
 * When is the next Monday after Mar, 20, 2020?
 * const result = nextDay(new Date(2020, 2, 20), 1)
 * => new Date(2020, 2, 23)
 *
 * @example
 * When is the next Tuesday after Mar, 21, 2020?
 * const result = nextDay(new Date(2020, 2, 21), 2)
 * => new Date(2020, 2, 24)
```

2021-02-25 07:52 UTC, kossnocorp approved these changes
Please make examples in both `nextMonday` and `nextDay` consistent with other functions and remove extra runtime checks. Just to reiterate, we don't remove `requiredArgs` because other functions use that, but in v3, we'll remove it.

2021-02-25 07:52 UTC, kossnocorp commented on src/nextDay/index.ts
> +export default function nextDay(date: Date | number, day: number): Date {
Let's instead of checking the type in runtime and throwing `throw new RangeError('Invalid Day')` use an alias for day: 
```suggestion
export default function nextDay(date: Date | number, day: Day): Date {
```

...and add to `types.ts`:

```ts
export type Day = 0 | 1 | 2 | 3 | 4 | 5 | 6
```

2021-02-25 07:52 UTC, kossnocorp commented on src/nextDay/index.ts
> +  }
Instead of adding runtime checks and adding extra bytes, let's give users a choice, use TypeScript/Flow or getting obscure errors when they misuse the API.

2021-02-25 07:52 UTC, kossnocorp commented on src/nextDay/index.ts
> + * => new Date(2020, 2, 24)
Please make the example consistent with other functions (see for example `addDays`: https://github.com/date-fns/date-fns/blob/master/src/addDays/index.ts#L25).

Just use `toString` on the date and cut off the timezone (to make it universal):

```js
new Date(2020, 2, 24).toString()
//=> "Tue Mar 24 2020 00:00:00 GMT+0800 (Singapore Standard Time)"
```

2021-02-25 07:52 UTC, kossnocorp commented on src/nextDay/index.ts
> + * @summary When is the next day of Week?
```suggestion
 * @summary When is the next day of the week?
```

2021-02-25 07:52 UTC, kossnocorp commented on src/nextMonday/index.ts
> + *  When is the next day of the week? 1 represents Monday.
```suggestion
 * When is the next Monday?
```

2021-02-28 11:18 UTC, tan75 commented on src/nextDay/index.ts
> +export default function nextDay(date: Date | number, day: number): Date {
Done

2021-03-04 06:45 UTC, kossnocorp approved these changes
👏

2021-03-04 06:47 UTC, merged