🚧 Migrate `getWeekOfMonth` to typescript
date-fns/date-fns pull request #2238
Opened 2021-02-23 02:23 UTC by codecog

TBC

2021-02-24 19:51 UTC, codecog commented
@kossnocorp I had issues running `./scripts/build/build.sh` as it throws an error to do with the docs. Have you run into this problem before?

2021-03-05 04:18 UTC, kossnocorp requested changes
Thank you for the pull request! Please address my comments. Docs generation will fix once you restore the original JSDoc. Also, please rebase from the master branch, where we fixed tests.

2021-03-05 04:18 UTC, kossnocorp commented on src/getWeekOfMonth/test.js
> -
Please keep this and the check in the code and also don't forget to keep `@throws` in the docs. I know that TypeScript solves the problem and we'll remove all type checks in v3, but this is a breaking change and we're not ready for a major release.

2021-03-05 04:18 UTC, kossnocorp commented on src/getWeekOfMonth/index.ts
> +export default getWeekOfMonth
Please rewrite to a normal function `export default function getWeekOfMonth`.

2021-03-05 04:18 UTC, kossnocorp commented on src/getWeekOfMonth/index.ts
> + */
Please preserve the original JSDoc, until v3 when all code is in TypeScript we're forced to use it.

2021-03-05 04:18 UTC, kossnocorp commented on src/getWeekOfMonth/index.js
> -}
Could you please rework your commit so git understands that it is a rename to preserve the git history?

2021-03-05 04:18 UTC, kossnocorp commented on src/getWeekOfMonth/index.ts
> +  { locale, weekStartsOn } = defaultOptions
Please assign type `LocaleOptions & WeekStartOptions` from https://github.com/date-fns/date-fns/blob/master/src/types.ts. Also `= defaultOptions` breaks when you pass any object, so please get rid of it and keep it in the code or `{ locale, weekStartsOn = 0 }`.

2021-03-16 18:21 UTC, closed without merging