migrate set function
date-fns/date-fns pull request #2251
Opened 2021-02-24 21:46 UTC by maximtop

This PR fixes: https://github.com/date-fns/date-fns-typescriptify/issues/120

2021-03-02 17:02 UTC, rikkalo approved these changes
Thank you for your contribution 👍

2021-03-04 07:20 UTC, kossnocorp requested changes
Thank you a lot, please move the interface to shared types cc @rikkalo

2021-03-04 07:20 UTC, kossnocorp commented on src/set/index.ts
> +
Could you please move it to `src/types.ts`

2021-03-04 07:43 UTC, maximtop commented on src/set/index.ts
> +
I've moved

2021-03-04 12:24 UTC, kossnocorp approved these changes
🙏

2021-03-04 12:27 UTC, merged