Add check for Feb 28 and 29 of the same year
date-fns/date-fns pull request #2256
Opened 2021-02-25 22:56 UTC by tan75

Add extra check to test if dates are either Feb 28 or Feb 29 of the same year
Add extra tests for intervalToDuration() to test the same

2021-02-26 00:43 UTC, kossnocorp approved these changes
Looks good!

2021-02-26 00:51 UTC, kossnocorp requested changes

2021-02-26 00:51 UTC, kossnocorp commented on src/differenceInMonths/test.js
> +  })
Please do the following:

1. Join these tests into a single one, as all of them have the same description
2. Move edge case tests to the end of the file, you might even wrap them into `describe('edge cases', ...` or `describe('regression tests', ...`

2021-02-26 00:51 UTC, kossnocorp commented on src/intervalToDuration/test.js
> +  })
Same here, join tests and move to the bottom.

Could you also fix the `Returns` -> `returns`.

2021-02-26 21:37 UTC, tan75 commented on src/differenceInMonths/test.js
> +  })
Done

2021-02-26 21:57 UTC, tan75 commented on src/intervalToDuration/test.js
> +  })
Done

2021-03-02 11:35 UTC, kossnocorp approved these changes
👍

2021-03-02 11:38 UTC, merged