i18n support for Albanian language
date-fns/date-fns pull request #2290
Opened 2021-03-05 07:36 UTC by arditdine

Following the guide here: https://date-fns.org/v2.18.0/docs/I18n-Contribution-Guide

I added support for the Albanian language.

2021-03-08 21:42 UTC, tan75 requested changes

2021-03-08 21:42 UTC, tan75 commented on src/locale/sq/_lib/localize/index.js
> +  return number
Hi @arditdine 
Thanks a lot for your contribution - support for Albanian language would be a great addition to this library!
We are currently reviewing your PR and here are our suggestions: 

It looks like this code returns `number` in any case. Hence would that be better just to return `number` here?

2021-03-09 04:04 UTC, arditdine commented on src/locale/sq/_lib/localize/index.js
> +  return number
I've updated this with some examples I managed to find online. 
https://sq.wikipedia.org/wiki/How_I_Met_Your_Mother_(sezoni_i_1-r%C3%AB)
https://sq.wikipedia.org/wiki/How_I_Met_Your_Mother_(sezoni_i_4-t)

For hours we don't use suffix so I return only the number.

2021-03-10 00:16 UTC, tan75 requested changes

2021-03-10 00:16 UTC, tan75 commented on src/locale/sq/index.js
> +    firstWeekContainsDate: 1
@arditdine could you please double-check this value: 
`firstWeekContainsDate: 1`
Wikipedia says its 4 in the EU and most of other European countries.
Have you got any sources to confirm if it is 1 or 4?

2021-03-10 01:49 UTC, arditdine commented on src/locale/sq/index.js
> +    firstWeekContainsDate: 1
Yes i've confirmed that it is 1. In date-fns documentation:
https://date-fns.org/v2.19.0/docs/I18n-Contribution-Guide#index.js

You have this link:
http://www.pjh2.de/datetime/weeknumber/wnd.php?l=en

2021-03-10 20:52 UTC, tan75 approved these changes
Thank you for your contribution!
Much appreciated!

2021-03-17 07:10 UTC, kossnocorp requested changes
Please add support for `parse`. It should be straightforward but feel free to ask any questions.

2021-03-17 07:10 UTC, kossnocorp commented on src/locale/sq/_lib/match/index.js
> +import buildMatchPatternFn from '../../../_lib/buildMatchPatternFn/index'
@arditdine please update patterns below, so it would fix `parse` (the third column should not have that mane `Invalid Date`: https://github.com/date-fns/date-fns/pull/2290/files#diff-b1642ead537bf233bdd80d82877ee7a3e3ff81641532ea7b4947ce6e242df01f)

2021-03-17 09:23 UTC, arditdine commented on src/locale/sq/_lib/match/index.js
> +import buildMatchPatternFn from '../../../_lib/buildMatchPatternFn/index'
Sorry my bad, didn't really understand why the last column was always `Invalid Date` but I've fixed the matching regex

2021-03-26 15:18 UTC, arditdine commented on src/locale/sq/_lib/match/index.js
> +import buildMatchPatternFn from '../../../_lib/buildMatchPatternFn/index'
@kossnocorp any updates on this?

2021-03-29 10:29 UTC, kossnocorp approved these changes

2021-03-29 10:29 UTC, kossnocorp commented on src/locale/sq/_lib/match/index.js
> +import buildMatchPatternFn from '../../../_lib/buildMatchPatternFn/index'
@arditdine thank you for updating the PR, it will come with the next version of the library.

2021-03-29 10:30 UTC, merged