Add nextWednesday, nextThursday, nextFriday, nextSaturday, nextSunday
date-fns/date-fns pull request #2291
Opened 2021-03-06 23:10 UTC by tan75

### New Features
nextWednesday, nextThursday, nextFriday, nextSaturday, nextSunday

2021-03-10 23:53 UTC, 0x24a537r9 commented
I think you probably want to run `sh scripts/build/build.sh` to rebuild the indices. I put up #2309 to fix `next(Day|Monday|Tuesday)` :)

2021-03-11 23:28 UTC, tan75 commented
> I think you probably want to run `sh scripts/build/build.sh` to rebuild the indices. When you do, you'll run into an issue where the `Day` type is not being properly created in the Flow types, so it might be a nontrivial fix

Thanks for a heads-up!
We haven't encountered it yet however if we do - we will fix it.

2021-03-12 08:57 UTC, kossnocorp commented
@0x24a537r9 could you please elaborate? I did release `v2.19.0` with `nextModay` and `nextTuesday`, did you have any problem with that?

2021-03-12 09:25 UTC, kossnocorp requested changes

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSaturday/index.ts
> + **/
`**/` hangs JSDoc parser, please replace it with `*/` here and everywhere (this is the correct JSDoc sequence `/** Comment */`.

2021-03-12 09:25 UTC, kossnocorp commented on src/nextFriday/test.ts
> +  it('returns `Invalid Date` if the given date is invalid', function () {
Please add space for consistency sake. Also in new tests code, we can use `() => {}`

```suggestion

  it('returns `Invalid Date` if the given date is invalid', () => {
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextFriday/index.ts
> +export default function nextFriday(date: Date | number): Date {
Please remove space and `**/` (see my other comment about it with more details).

```suggestion
 */
export default function nextFriday(date: Date | number): Date {
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSaturday/index.ts
> +export default function nextSaturday(date: Date | number): Date {
```suggestion
export default function nextSaturday(date: Date | number): Date {
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextFriday/index.ts
> + * @throws {TypeError} the date should be a valid date
I don't think it's still true

```suggestion
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSaturday/index.ts
> + * @throws {TypeError} the date should be a valid date
```suggestion
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextFriday/index.ts
> + * @param {Date | number} date the date to check
```suggestion
 * @param {Date | number} date - the date to start counting from
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextFriday/index.ts
> + * @returns {Date} the date is the next Friday
```suggestion
 * @returns {Date} the next Friday
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextMonday/index.ts
> + * @param {Date | number} date the date to check
```suggestion
 * @param {Date | number} date - the date to start counting from
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextMonday/index.ts
> + * @returns {Date} the date is the next Monday
```suggestion
 * @returns {Date} the next Monday
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextMonday/index.ts
> + * @throws {TypeError} the date should be a valid date
```suggestion
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSaturday/index.ts
> + * @param {Date | number} date the date to check
```suggestion
 * @param {Date | number} date - the date to start counting from
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSaturday/test.ts
> +  it('returns `Invalid Date` if the given date is invalid', function () {
```suggestion
  })

  it('returns `Invalid Date` if the given date is invalid', () => {
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSunday/index.ts
> + * @param {Date | number} date the date to check
```suggestion
 * @param {Date | number} date - the date to start counting from
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSaturday/index.ts
> + * @returns {Date} the date is the next Saturday
```suggestion
 * @returns {Date} the next Saturday
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSunday/index.ts
> + * @returns {Date} the date is the next Sunday
```suggestion
 * @returns {Date} the next Sunday
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSunday/index.ts
> + * @throws {TypeError} the date should be a valid date
```suggestion
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSunday/index.ts
> +export default function nextSunday(date: Date | number): Date {
```suggestion
 */
export default function nextSunday(date: Date | number): Date {
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSaturday/index.ts
> + **/
```suggestion
 */
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextSunday/test.ts
> +  it('returns `Invalid Date` if the given date is invalid', function () {
```suggestion
  })

  it('returns `Invalid Date` if the given date is invalid', () => {
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextThursday/index.ts
> +export default function nextThursday(date: Date | number): Date {
```suggestion
 * @param {Date | number} date - the date to start counting from
 * @returns {Date} the next Thursday
 * @throws {TypeError} 1 argument required
 *
 * @example
 * When is the next Thursday after Mar, 22, 2020?
 * const result = nextThursday(new Date(2020, 2, 22))
 * => Thur Mar 26 2020 00:00:00
 */
export default function nextThursday(date: Date | number): Date {
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextThursday/test.ts
> +  it('returns `Invalid Date` if the given date is invalid', function () {
```suggestion
  })

  it('returns `Invalid Date` if the given date is invalid', () => {
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextTuesday/index.ts
> + * @throws {TypeError} 1 argument required
```suggestion
 * @param {Date | number} date - the date to start counting from
 * @returns {Date} the next Tuesday
 * @throws {TypeError} 1 argument required
```

2021-03-12 09:25 UTC, kossnocorp commented on src/nextWednesday/index.ts
> +export default function nextWednesday(date: Date | number): Date {
```suggestion
 * @param {Date | number} date - the date to start counting from
 * @returns {Date} the next Wednesday
 * @throws {TypeError} 1 argument required
 *
 * @example
 * When is the next Wednesday after Mar, 22, 2020?
 * const result = nextWednesday(new Date(2020, 2, 22))
 * => Wed Mar 25 2020 00:00:00
 */
export default function nextWednesday(date: Date | number): Date {
```

2021-03-13 22:01 UTC, tan75 commented on src/nextSaturday/index.ts
> + **/
Done.

2021-03-15 03:07 UTC, kossnocorp approved these changes
Thank you a lot 👏

2021-03-15 03:08 UTC, merged