Migrate getWeek function
date-fns/date-fns pull request #2318
Opened 2021-03-11 21:36 UTC by jooola

Fixes https://github.com/date-fns/date-fns-typescriptify/issues/58

2021-04-13 21:13 UTC, tan75 commented on src/getWeek/index.ts
> +}
Could you please use the existing types from [types.ts](https://github.com/date-fns/date-fns/blob/master/src/types.ts)

2021-04-13 21:14 UTC, tan75 requested changes
Thank you for your contribution! Could you please address my comments? Many thanks!

2021-04-14 17:24 UTC, jooola commented on src/getWeek/index.ts
> +}
Ok, it should be fixed now.

2021-04-14 17:35 UTC, jooola commented on src/getWeek/index.ts
> +export default function getWeek(dirtyDate: Date | number, options?: LocaleOptions & WeekStartOptions & FirstWeekContainsDateOptions): number {
@tan75 I was wondering, should I default the options to an empty object or is it better to allow it to be undefined ?

2021-04-15 20:56 UTC, tan75 commented on src/getWeek/index.ts
> +export default function getWeek(dirtyDate: Date | number, options?: LocaleOptions & WeekStartOptions & FirstWeekContainsDateOptions): number {
I don't think so.
I defaulted the options to an empty object during the migration of `getWeekYear` and surprisingly introduced a breaking change - you can see the fix in this PR - 
[PR](https://github.com/date-fns/date-fns/pull/2423/files#diff-f4381187a2ef5a29864dc44990590030b44dedb7d9772ed895724a7abd11b2bbL56)

2021-04-15 21:04 UTC, tan75 approved these changes
Thank you for your contribution!

2021-04-15 21:04 UTC, tan75 commented
@jooola thanks a lot for your work!
I spotted you changed the `FirstWeekContainsDate` values in `types.ts` and just wanted to mention that according to 
[Wikipedia Week Numbering](https://en.wikipedia.org/wiki/Week#Week_numbering) is is always either 1 or 4 (and our Locales can prove it) so I changed it back to `1 | 4`

2021-04-16 07:30 UTC, kossnocorp commented on src/types.ts
> +
In the future, please avoid introducing random changes like this. You probably had good intentions and logic behind those, but they aren't evident and produce unnecessary noise and potential merge conflicts for maintainers.

2021-04-16 07:35 UTC, merged

2021-04-16 10:13 UTC, jooola commented on src/types.ts
> +
Haha, this wasn't random, I followed the documentation, which state that it could have been 1-7 and I didn't know what @tan75 just said. But yeah, my bad, sorry for the noise !

I would suggest adding a comment for the type, as it should be documented anyway, and reduce unawareness from dumb contributors.