Upgrade huksy and lint-staged dependencies
date-fns/date-fns pull request #2319
Opened 2021-03-11 22:03 UTC by jooola

Upgraded huksy and lint-staged dependencies with some extra changes :
- Added subfolders and .ts files to the lint-staged glob pattern
- New husky layout with .huksy folder and hooks inside

2021-03-22 03:26 UTC, kossnocorp requested changes
Thank you for the contribution. Could you please describe in a paragraph what does this update provides and also address my comments?

2021-03-22 03:26 UTC, kossnocorp commented on package.json
> +    "postinstall": "husky install",
What's the point of this? Won't it will affect all users installing date-fns?

I can see they recommend using pinst: https://typicode.github.io/husky/#/?id=yarn-v2

2021-03-22 03:26 UTC, kossnocorp commented on .husky/pre-commit
> +. "$(dirname "$0")/_/husky.sh"
I am not sure if you can verify that it works, but could you please add support for Windows? (There're few paragraphs about that in the documentation).

2021-04-08 17:22 UTC, jooola commented on package.json
> +    "postinstall": "husky install",
This project seem to use Yarn v1, I replace the `postinstall` to the `prepare` lifecycle.

If yarn v2 is used, we will need to change this.

2021-04-08 17:24 UTC, jooola commented on .husky/pre-commit
> +. "$(dirname "$0")/_/husky.sh"
I added the small helper for windows, it should be working.

2021-04-08 17:27 UTC, jooola commented
The main pros of the new versions are that husky is really lightweight and allow to run any kind of scripts (bash, node, python).

Other than that, it simply keep the project dependencies up to date.

2021-04-14 04:18 UTC, kossnocorp commented on package.json
> +    "postinstall": "husky install",
I mean users that install date-fns will have this command run and throw an error.

2021-04-14 04:18 UTC, kossnocorp commented
@jooola got you, thanks, please fix the issue with `postinstall`.

2021-04-14 17:10 UTC, jooola commented
@kossnocorp Fixed the postinstall issue. I guess we cannot enforce the use of husky on the developer side.

2022-04-18 20:01 UTC, jooola commented
Closing in favor of #2899

2022-04-18 20:01 UTC, closed without merging