Migrate `getWeekOfMonth` to TypeScript
date-fns/date-fns pull request #2332
Opened 2021-03-17 01:17 UTC by varwasabi

I've addressed previous feedback here and have re-opened the PR. @kossnocorp please let me know if there's anything else for this. I also note that after running `./scripts/build/build.sh`, there's quite a lot of changes. I've opened this under the assumption that those files will be committed at a later time once the major version bump takes place.

2021-03-17 02:48 UTC, kossnocorp requested changes
Thanks, looks good besides the confusion with the options type.

2021-03-17 02:48 UTC, kossnocorp commented on src/getWeekOfMonth/index.ts
> +}
```suggestion
```

2021-03-17 02:48 UTC, kossnocorp commented on src/getWeekOfMonth/index.ts
> +  dirtyOptions: Options
```suggestion
  dirtyOptions: LocaleOptions & WeekStartOptions
```

2021-03-17 02:50 UTC, kossnocorp commented on src/getWeekOfMonth/index.ts
> +  dirtyOptions: LocaleOptions & WeekStartOptions
```suggestion
  dirtyOptions?: LocaleOptions & WeekStartOptions
```

2021-03-17 08:29 UTC, varwasabi commented
@kossnocorp Thanks for the feedback and the assistance, should be ready to merge now.

2021-03-29 10:42 UTC, kossnocorp requested changes
Please recover this exception and also migrate the test file.

2021-03-29 10:42 UTC, kossnocorp commented on src/getWeekOfMonth/index.ts
> -  }
This is a breaking change we plan to introduce in v3, but we still need this check while we migrate the library in v2. Please recover those lines.

2021-07-10 17:44 UTC, closed without merging