Migrate setWeek function
date-fns/date-fns pull request #2340
Opened 2021-03-18 21:12 UTC by maximtop

This pr fixes: https://github.com/date-fns/date-fns-typescriptify/issues/133

2021-03-23 10:02 UTC, kossnocorp requested changes
Looks good, but I think it worth extracting type alias.

2021-03-24 20:05 UTC, maximtop commented on src/types.ts
> +
@kossnocorp i've extracted

2021-03-29 10:23 UTC, kossnocorp approved these changes

2021-03-29 10:23 UTC, kossnocorp commented on src/setWeekYear/index.ts
> +import { LocaleOptions, WeekStartOptions, WeekYearStartOptions } from '../types';
```suggestion
import { LocaleOptions, WeekStartOptions, WeekYearStartOptions } from '../types'
```

2021-03-29 10:23 UTC, kossnocorp commented on src/setWeekYear/index.ts
> +    dirtyOptions?: LocaleOptions & WeekStartOptions & WeekYearStartOptions,
```suggestion
    options: LocaleOptions & WeekStartOptions & WeekYearStartOptions = {},
```

2021-03-29 10:23 UTC, kossnocorp commented on src/setWeekYear/index.ts
> +  const options = dirtyOptions || {}
```suggestion
```

2021-03-29 10:24 UTC, kossnocorp commented
Something funny happened to GitHub. Dismiss my review up to this point.

2021-03-29 10:38 UTC, kossnocorp requested changes

2021-03-29 10:38 UTC, kossnocorp commented on src/types.ts
> +
Please sync with @tan75 https://github.com/date-fns/date-fns/pull/2375/files#r603154585

2021-06-03 03:14 UTC, kossnocorp approved these changes
✌

2021-06-03 03:14 UTC, merged