Migrate de locale
date-fns/date-fns pull request #2365
Opened 2021-03-23 09:55 UTC by maximtop

This pr fixes: https://github.com/date-fns/date-fns-typescriptify/issues/154

2021-03-24 11:47 UTC, kossnocorp requested changes
Great job! Please format using Prettier config, use `import type` where possible, modernize the code, simplify types, and get rid of extra type conversions (`Number()`; of course if it's possible).

2021-03-24 11:47 UTC, kossnocorp commented on src/locale/de/_lib/formatDistance/index.ts
> +import { FormatDistanceFn } from '../../../types';
Your Prettier seems off, please setup to automatically format the code using the repo settings.

I also suggest always using `import { FormatDistanceFn } from '../../../types'` when importing only types.

2021-03-24 11:47 UTC, kossnocorp commented on src/locale/de/_lib/formatRelative/index.ts
> +const formatRelative: FormatRelativeFn = function formatRelative(token, _date, _baseDate, _options) {
While I prefer using `function name() {...` in this case (given that we verify `FormatRelativeFn`) it's better using `() => {...`:

```suggestion
const formatRelative: FormatRelativeFn = formatRelative(token, _date, _baseDate, _options) => {
```

2021-03-24 11:47 UTC, kossnocorp commented on src/locale/de/_lib/localize/index.ts
> +const ordinalNumber: LocalizeFn<number> = function ordinalNumber(dirtyNumber, _dirtyOptions) {
Here too, I think it's better to not mix `() =>` and `function ()`, it's just confusing.

2021-03-24 11:47 UTC, kossnocorp commented on src/locale/de/_lib/localize/index.ts
> +    argumentCallback: function(quarter: unknown) {
Can't we actually ensure that `quarter` is always a number and get rid of `Number(quarter)`?

2021-03-24 11:47 UTC, kossnocorp commented on src/locale/de/_lib/localize/index.ts
> +    argumentCallback: function(quarter: unknown) {
I would also modernize the function while we at it: `argumentCallback: (quarter) =>quarter - 1`

2021-03-24 11:47 UTC, kossnocorp commented on src/locale/de/_lib/match/index.ts
> +    valueCallback: function(index: number) {
I hoped that `valueCallback`'s argument could be inferred from `Match`. Curious why it doesn't work?

2021-03-24 18:38 UTC, maximtop commented on src/locale/de/_lib/match/index.ts
> +    valueCallback: function(index: number) {
actually I do not know, maybe because buildMatchFn is not typed yet

2021-03-24 19:49 UTC, maximtop commented on src/locale/de/_lib/formatDistance/index.ts
> +import { FormatDistanceFn } from '../../../types';
> I also suggest always using import { FormatDistanceFn } from '../../../types' when importing only types.

To use import type I had to update babel dependencies because babel introduced support of import type only from [version 7.9 ](https://babeljs.io/blog/2020/03/16/7.9.0#typescript-38-type-only-imports-and-exports-11171httpsgithubcombabelbabelpull11171)

2021-03-24 19:51 UTC, maximtop commented
> Great job! Please format using Prettier config, use `import type` where possible, modernize the code, simplify types, and get rid of extra type conversions (`Number()`; of course if it's possible).

Prettier generated extra load for the reviewer)

2021-06-03 03:01 UTC, kossnocorp approved these changes
Let's go!

2021-06-03 03:01 UTC, merged

2021-08-09 08:13 UTC, cheeZery commented
Just wanted to say that although I like the extra punctuation in German months abbreviations (e.g. "Feb." instead of "Feb.", see https://github.com/date-fns/date-fns/blob/master/src/locale/de/_lib/localize/index.ts#L22), it makes working with different languages in one code base harder because of the inconsistency.
So if you want a date with an abbrivated month, thanks to this PR working with German dates got a whole lot easier: `2021-02-01` becomes "01. Feb. 21" with `dd. MMM yy`, `2021-05-01` on the other hand results in "01. Mai 21", so without a dot. But if you work with English dates as well, it will be "01. Feb 21" and "01. May 21", both without a dot.