isDate function to TypeScript
date-fns/date-fns pull request #2386
Opened 2021-03-30 10:57 UTC by tan75

#### Changes
Migrate isDate() to TS
Fix bug - see discussion 2338

This closes https://github.com/date-fns/date-fns-typescriptify/issues/66

2021-03-31 01:30 UTC, kossnocorp requested changes
Please remove the fix for #2338 from the PR. See: https://github.com/date-fns/date-fns/discussions/2338#discussioncomment-550803

2021-03-31 14:15 UTC, tan75 commented
> Please remove the fix for #2338 from the PR. See: [#2338 (comment)](https://github.com/date-fns/date-fns/discussions/2338#discussioncomment-550803)

Done.

2021-04-01 10:50 UTC, kossnocorp commented on src/isDate/index.ts
> + * @param {any} value - the value to check
```suggestion
 * @param {unknown} value - the value to check
```

2021-04-01 10:50 UTC, kossnocorp commented on src/isDate/index.ts
> +export default function isDate(value: any): value is Date {
```suggestion
export default function isDate(value: unknown): value is Date {
```

2021-04-08 03:29 UTC, kossnocorp approved these changes
🙏

2021-04-08 03:29 UTC, merged