migrate lightFormat to ts
date-fns/date-fns pull request #2395
Opened 2021-04-03 16:24 UTC by a-korzun

fixes https://github.com/date-fns/date-fns-typescriptify/issues/113

2021-04-13 16:20 UTC, tan75 approved these changes
Thank you!

2021-04-13 21:28 UTC, tan75 commented on src/lightFormat/index.ts
>   * var result = lightFormat(new Date(2014, 1, 11), 'yyyy-MM-dd')
Could you please change `var` to `const` in the examples as well?

2021-04-13 21:28 UTC, tan75 requested changes
Please change `var` to `const` in the examples.

2021-04-14 07:21 UTC, a-korzun commented
> Please change `var` to `const` in the examples.

Fixed

2021-04-19 21:01 UTC, tan75 approved these changes
Much appreciated!

2021-05-05 06:07 UTC, merged