creating unit conversions functions
date-fns/date-fns pull request #2433
Opened 2021-04-20 12:05 UTC by LucasHFS

Attempt to solve #732 . This is my first PR to the lib, any changes needed let me know.

2021-04-26 13:16 UTC, wenderjean commented on src/daysToWeeks/test.ts
> +    const result = daysToWeeks(14);
You could exercise your function a bit more I mean, giving it different values like `5`, `13`, `8`

2021-04-27 16:28 UTC, tan75 commented
@LucasHFS 
Thanks a lot for your work!
Could you please fix all the examples in your files as per this commit below: 
[Commit](https://github.com/date-fns/date-fns/pull/2433/files#diff-91ef18f1c7c67a10134478750473345429e9746a3ec075f0d07ce69ad107c83aR16-R19)

As well, could you please add more tests to your test files like 
` daysToWeeks(13);` - see the comment from @wenderjean 
From my point of view, I would expect the result of the above call to be `1`

2021-04-27 22:28 UTC, tan75 requested changes
Thank you for your PR! Please, address my comments.

2021-04-27 23:45 UTC, LucasHFS commented
> From my point of view, I would expect the result of the above call to be `1`

@tan75 I get it,  can I use this logic in similar situations, e.g. minutesToHours & monthsToYears?

2021-04-28 11:03 UTC, tan75 commented
> > From my point of view, I would expect the result of the above call to be `1`
> 
> @tan75 I get it, can I use this logic in similar situations, e.g. minutesToHours & monthsToYears?

Yes, you can. 
I think it makes sense.

2021-04-28 13:03 UTC, LucasHFS commented on src/daysToWeeks/test.ts
> +    const result = daysToWeeks(14);
Done. 😃

2021-05-12 22:45 UTC, tan75 approved these changes
Many thanks for your PR!

2021-05-14 04:34 UTC, kossnocorp requested changes
Thank you so much for your great work! 

The only problem I found in the PR is that test examples focus on what a test does instead of the function behavior. Please rewrite those using the example I added for `millisecondsToMinutes`.

Please rewrite tests

2021-05-14 04:34 UTC, kossnocorp commented on src/millisecondsToMinutes/test.ts
> +})
Please take a look at this test file. I want you to rewrite tests in the PR to make them look like this.

Instead of focusing on what test does `converts 700 milliseconds to seconds` I want you describe behavior and test it. It's enough to have a couple of similar examples that test the same thing:

```ts
assert(millisecondsToMinutes(60000) === 1)
assert(millisecondsToMinutes(120000) === 2)
```

Also, when a function does rounding, I want you to add an example for that (please make sure that the first test doesn't check for rounding).

And finally, test border values (float and zero).

2021-05-23 09:25 UTC, tan75 commented
hi @LucasHFS 

Hope all is well. Just wondering if you are still working on this PR?

2021-05-24 14:11 UTC, LucasHFS commented
@tan75 Yep, I'll send the requested changes today.

2021-05-28 05:51 UTC, kossnocorp approved these changes

2021-05-28 05:51 UTC, merged