Add Bosnian locale
date-fns/date-fns pull request #2495
Opened 2021-05-28 16:03 UTC by BranislavLazic

This PR adds Bosnian locale and resolves this issue https://github.com/date-fns/date-fns/issues/2435.

2021-05-28 16:08 UTC, sake92 commented on src/locale/bs/_lib/formatRelative/index.js
> +        return "'sledeće nedjelje u' p"
I think that `sljedeće` is correct one here.

2021-05-28 16:10 UTC, sake92 commented on src/locale/bs/_lib/formatRelative/index.js
> +        return "'sledeće nedjelje u' p"
Also `sedmica` instead of `nedjelja`.

2021-05-28 16:20 UTC, BranislavLazic commented on src/locale/bs/_lib/formatRelative/index.js
> +        return "'sledeće nedjelje u' p"
Fixed. Thank you!

2021-06-02 20:50 UTC, tan75 requested changes

2021-06-02 20:50 UTC, tan75 commented on src/locale/bs/index.js
> +    firstWeekContainsDate: 1,
hi @BranislavLazic 
Could you please provide a reference that confirms the value of 1 of `firstWeekContainsDate`? 
According to Wikipedia, it is 4 for the majority of European countries. 
Do you possibly know a source that we can refer to?

2021-06-02 22:18 UTC, BranislavLazic commented on src/locale/bs/index.js
> +    firstWeekContainsDate: 1,
Seems like you are right. Also, some of them share the same flaw. E.g. sr-Latn (which was my reference locale) or hr.

2021-06-03 22:19 UTC, tan75 commented
@BranislavLazic 
could you please re-generate snapshots by running `yarn locale-snapshots` and commit the results?

2021-06-03 22:20 UTC, tan75 requested changes
Please run `yarn locale-snapshots` and commit the results.

2021-06-04 20:05 UTC, tan75 approved these changes
Much appreciated! 👍  👍  
I will schedule this for our next release given the go-ahead by @kossnocorp

2021-07-23 05:41 UTC, merged