Add clamp function
date-fns/date-fns pull request #2498
Opened 2021-06-04 12:17 UTC by Liam-Tait

Add a function to clamp a date based on an interval.

This function ensures that a date is bounded by a minimum and maximum

2021-06-07 23:14 UTC, Liam-Tait commented
For the curried version of this function.  Currying from the right makes sense for my use case. I have an interval that I want to clamp multiple values to.

```typescript
const contractInterval = {start, end}
const clampToContract =  clamp(allowed)

const queryStartDate = new Date();
const queryEndDate = new Date();

const start = clampToContract(queryStartDate)

```

2021-06-07 23:15 UTC, Liam-Tait commented
Sorry @tan75, I accidentally closed the PR

2021-06-10 21:56 UTC, tan75 requested changes
Hi @Liam-Tait
this function is a great idea and it might be very useful! Thank you for your PR! 👍 
Could you please make the examples consistent with our current example convention - e.g. see this one below:
[Next Monday example](https://github.com/date-fns/date-fns/blob/master/src/nextMonday/index.ts#L18-L21)
Now the convention is to use `const` and please delete the 'javascript' mention.
As well, please format the examples and the 'Docs' part of the file - it's good to have them consistent with the `nextMonday` example. Let us know if anything is unclear.

2021-06-10 21:56 UTC, tan75 commented on src/clamp/index.ts
> + * var interval = {
Could you please change `var` to `const` in your examples?

2021-06-10 21:57 UTC, tan75 commented
@Liam-Tait 
could you please provide any use cases for `clamp`?

2021-06-11 09:30 UTC, Liam-Tait commented on src/clamp/index.ts
> + * var interval = {
Can do.
Is it preferable to write the example as typescript?

2021-06-14 23:02 UTC, tan75 commented on src/clamp/index.ts
> + * var interval = {
> Can do.
> Is it preferable to write the example as typescript?

No, JS is ok in case if a user doesn't use TS.

2021-06-19 04:58 UTC, Liam-Tait commented on src/clamp/index.ts
> + * var interval = {
Resolved with 68d41b2

2021-06-19 05:19 UTC, Liam-Tait commented
> Hi @Liam-Tait
> this function is a great idea and it might be very useful! Thank you for your PR! 👍

Thanks!

> Could you please make the examples consistent with our current example convention - e.g. see this one below:
> [Next Monday example](https://github.com/date-fns/date-fns/blob/master/src/nextMonday/index.ts#L18-L21)
> Now the convention is to use `const` and please delete the 'javascript' mention.
> As well, please format the examples and the 'Docs' part of the file - it's good to have them consistent with the `nextMonday` example. Let us know if anything is unclear.

I think I have matched the convention. Let me know if this correct

- use `const` instead of `var`
- removed javascript mention
- removed backtick code section
- inline parameters instead of using seperate variables
- Add comment for the question the function is answering
- Add comment for the returned value

2021-06-19 05:39 UTC, Liam-Tait commented
> @Liam-Tait
> could you please provide any use cases for `clamp`?

My use case is for querying a list of data based on a contract. 

The query has a minDate and maxDate
The contract has a start and end
The data has a date 

I only want to retrieve the data within the period of a contract.
In order to do this i want to clamp the query minDate  and max Date to the contract interval.

Ideally this would be done at the database layer, however that option is not available to me.
```javascript
const minDate = clamp(requestedMin, contractInterval)
const maxDate = clamp(requestedMax, contractInterval)
const result = query(minDate, maxDate)
```

---
Useful for when there is an allowed period of time (interval) and a user input of date and instead of causing an error bounding to the allowed range

2021-06-19 05:41 UTC, Liam-Tait commented
Updated! Please take a look

2021-06-19 20:57 UTC, tan75 approved these changes
@Liam-Tait Thank you for this PR!  👍 
Assigned to @kossnocorp for release

2021-07-23 05:50 UTC, merged