adding previoursDay and its variations
date-fns/date-fns pull request #2522
Opened 2021-06-18 15:04 UTC by LucasHFS

Implements #2507 request, and similar functions.

2021-06-18 17:06 UTC, tan75 commented
Hi @LucasHFS 
thanks a mill!
I linked the mentioned issue to this PR and marked it as WIP until it gets approval.
Can you please have a look into this test as it is failing?

```
  41 |   it('returns the previous Tuesday given the Saturday after it', function () {
    > 42 |     assert.deepStrictEqual(
```

if you prefer to run tests locally you can do 
`yarn test`

Many thanks!

2021-06-18 20:39 UTC, fturmel commented
Minor stuff, but you have a little typo in your tests (_previours_ instead of _previous_).

Could I also propose a simpler and faster (by about 50%) implementation for `previousDay`? `nextDay` could be refactored using the same approach as well.

```typescript
export default function previousDay(dirtyDate: Date | number, day: Day): Date {
  requiredArgs(2, arguments)

  const date = toDate(dirtyDate)

  let delta = getDay(date) - day
  if (delta <= 0) delta += 7

  return subDays(date, delta)
}
```

2021-06-21 13:35 UTC, fturmel commented
@LucasHFS @tan75 

There's already a PR for the `nextDay` optimization that has been approved (#2524). Should the change be reverted here or should I close 2524?

2021-06-22 16:53 UTC, tan75 commented
> @LucasHFS @tan75
> 
> There's already a PR for the `nextDay` optimization that has been approved (#2524). Should the change be reverted here or should I close 2524?

This PR 2524 will be included in our next release hopefully soon enough.
And https://github.com/date-fns/date-fns/pull/2522 can be added after. If any conflicts - we will fix it!

Thanks guys! 👍   🥇

2021-07-30 14:12 UTC, tan75 approved these changes
Thanks a lot for your contribution! 🚀

2021-07-30 15:30 UTC, fturmel commented
Just had a look again at this PR and I think there's no need to convert the date argument using `toDate` before passing it to `previousDay`. This optimization applies to all the next* functions as well (nextMonday, etc).

ex:
```js
export default function previousThursday(date: Date | number): Date {
  requiredArgs(1, arguments)
  return previousDay(toDate(date), 4)
}
```

could simply be:
```js
export default function previousThursday(date: Date | number): Date {
  requiredArgs(1, arguments)
  return previousDay(date, 4)
}
```

2021-07-30 23:12 UTC, tan75 commented
@fturmel this totally makes sense! 
Will need to change the next* ones in a separate PR.

2021-08-19 05:16 UTC, kossnocorp requested changes

2021-08-19 05:16 UTC, kossnocorp commented on src/previousSunday/index.ts
> + * //=> Fri June 20 2021 00:00:00
Wrong output

2021-08-19 05:16 UTC, kossnocorp commented on src/previousSaturday/index.ts
> + * //=> Fri June 19 2021 00:00:00
Wrong

2021-09-11 18:49 UTC, tan75 commented on src/previousSunday/index.ts
> + * //=> Fri June 20 2021 00:00:00
✅. Fixed

2021-09-11 19:13 UTC, tan75 commented on src/previousSaturday/index.ts
> + * //=> Fri June 19 2021 00:00:00
✅   Fixed

2021-09-16 04:55 UTC, kossnocorp commented on src/previousDay/index.ts
> + * @param {Day} day - day of the week
```suggestion
 * @param {number} day - day of the week
```

2021-09-16 05:18 UTC, kossnocorp approved these changes

2021-09-16 05:19 UTC, merged