converting -0 to 0 when it appears
date-fns/date-fns pull request #2571
Opened 2021-08-01 15:45 UTC by LucasHFS

Attempt to solve #2555 .
handled the possibility of getting result -0 in all uses of Math.ceil and converted it in 0

2021-08-02 12:08 UTC, wenderjean commented on src/differenceInSeconds/index.ts
> +}
You a new-line problem here.

2021-08-02 12:08 UTC, wenderjean commented on src/utils/removesNegativeZeroIfPresent/index.ts
> +    return Object.is(number, -0) ? 0 : number
The indentation does not follow the project pattern for those files you created.

2021-08-02 12:08 UTC, wenderjean commented on src/differenceInHours/index.ts
> +  return removesNegativeZeroIfPresent(diff > 0 ? Math.floor(diff) : Math.ceil(diff))
The same pattern repeats for all those pieces of code using `removesNegativeZeroIfPresent`, I mean, `diff > 0 ? Math.floor(diff) : Math.ceil(diff)`. What do u think about moving it to the utility function itself?

2021-08-02 15:15 UTC, LucasHFS commented on src/differenceInSeconds/index.ts
> +}
solved!

2021-08-02 15:16 UTC, LucasHFS commented on src/utils/removesNegativeZeroIfPresent/index.ts
> +    return Object.is(number, -0) ? 0 : number
fixed

2021-08-02 15:19 UTC, LucasHFS commented on src/differenceInHours/index.ts
> +  return removesNegativeZeroIfPresent(diff > 0 ? Math.floor(diff) : Math.ceil(diff))
I agree that's a better way to approach it. I did it in the last commit.

2021-08-04 08:29 UTC, pabrodez commented
Should date-fns still give the choice of how to round a value? #2511

2021-08-05 19:39 UTC, tan75 commented
> After this PR, should date-fns still give the choice of how to round a value? #2511

Good point! 
We've discussed this PR internally and have a couple of ideas - I will need to make some changes to these PRs.
The response to your question is 'Yes' - a rounding method will be passed in as an option with `Math.floor` as a default value.

2021-08-19 04:50 UTC, kossnocorp requested changes

2021-08-19 04:50 UTC, kossnocorp commented on src/_lib/getRoundingFn/index.ts
> +  }[method]
@tan75 please extract the object outside the function. Also, `trunc` method (which is the default in date-fns) is missing.

2021-08-19 04:50 UTC, kossnocorp commented on src/differenceInHours/index.ts
> +import getRoundedValue from '../utils/getRoundedValue'
```suggestion
import getRoundedValue from '../utils/getRoundedValue/index'
```

2021-08-19 04:50 UTC, kossnocorp commented on src/_lib/getRoundingFn/index.ts
> +export default function getRoundingFn(method: RoundingMethod) {
Please set the return type `: (input: number) => number`

2021-09-04 22:19 UTC, fturmel commented on src/differenceInWeeks/test.ts
> +      'ceil'
Shouldn't this argument be either 'trunc' or removed, and the assertion === 1?

2021-09-05 14:10 UTC, tan75 commented on src/differenceInWeeks/test.ts
> +      'ceil'
@fturmel 
yes, you are right! my bad!

2021-09-05 14:11 UTC, tan75 commented on src/differenceInWeeks/test.ts
> +      'ceil'
✅  fixed

2021-09-07 04:56 UTC, kossnocorp requested changes

2021-09-07 04:56 UTC, kossnocorp commented on src/_lib/roundingMethods/index.ts
> +  trunc: (value: number) => parseInt(value.toString()), // Math.trunc is not supported by IE
```suggestion
  trunc: (value: number) => value < 0 ? Math.ceil(value) : Math.floor(value), // Math.trunc is not supported by IE
```

[Benchmark](https://perf.link/#eyJpZCI6ImtoZnN0ZThnbzlyIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImZ1bmN0aW9uIG1hdGhUcnVuYyAodmFsdWUpIHsgcmV0dXJuIHZhbHVlIDwgMCA%2FIE1hdGguY2VpbCh2YWx1ZSkgOiBNYXRoLmZsb29yKHZhbHVlKSB9XG5mdW5jdGlvbiBwYXJzZVRydW5jKHZhbHVlKSB7IHJldHVybiBwYXJzZUludCh2YWx1ZS50b1N0cmluZygpKSB9IiwidGVzdHMiOlt7Im5hbWUiOiJGaW5kIGl0ZW0gMTAwIiwiY29kZSI6Im1hdGhUcnVuYygtMS45KSIsInJ1bnMiOlsyMjAwMDAsMTQ2NTAwMCw0OTUwMDAsMjI2MTAwMCw0MTMyMDAwLDI5MjAwMCw5MDMwMDAsMzE2OTAwMCwxMzAwMCwyNDk3MDAwLDIyMDAwLDEzMDAwLDcxMTAwMCwyMzAwMCwyNDc4MDAwLDIyMDAwLDEzMDAwLDIwNTgwMDAsOTM1MDAwLDIyMjgwMDAsMjQyMDAwMCwxMDkwMDAwLDEzNDMwMDAsOTA0MDAwLDE3NTEwMDAsMTUwMDAwLDIyODMwMDAsMTAwMCw0NjU2MDAwLDIxNjgwMDAsNTg4MDAwLDc5MzAwMCwyMTQyMDAwLDMzMjAwMDAsMjM0MDAwLDE1ODAwMDAsMTUzMTAwMCwxMzAwMCwzMTg4MDAwLDEzMDAwLDEzMDAwLDIzMjYwMDAsMzI2OTAwMCwxNjE4MDAwLDMxNjAwMDAsMTI0NzAwMCwzNDEyMDAwLDQyMzAwMDAsMTMwMDAsMzc4NjAwMCwyNDcxMDAwLDMyNzcwMDAsMjM1NjAwMCwxNzMwMDAsOTQ1MDAwLDMzMTkwMDAsMjM3ODAwMCwyNTIwMDAsMTMwMDAsMzMxNTAwMCwxMzAwMCwxMzAwMCw0NDY2MDAwLDE2NjgwMDAsMTAwMCwxMzAwMCw0MzMxMDAwLDE3NjgwMDAsMzM0MDAwLDEzMDAwLDEwNTkwMDAsMTMwMDAsMjIwMDAsMjE5OTAwMCw2ODAwMDAsNDY3MDAwLDU1MzAwMCw0MzA0MDAwLDE0MDAwLDIyMDAwLDI5OTAwMCw2NTkwMDAsOTk1MDAwLDIyMDAwLDMzMjIwMDAsMTczMzAwMCwxNzk2MDAwLDMyODUwMDAsMjU4ODAwMCwzNTY3MDAwLDQwNjcwMDAsNTYwMDAwLDI3MDAwLDIzNzAwMCwzMjMzMDAwLDMyMTQwMDAsMTAwMCwzMDcwMDAsMzM4NTAwMCwyMDMwMDAwXSwib3BzIjoxNTI5NzEwfSx7Im5hbWUiOiJGaW5kIGl0ZW0gMjAwIiwiY29kZSI6Ik1hdGgudHJ1bmMoLTEuOSkiLCJydW5zIjpbMzIxODAwMCwyMTAwMCwxODAwMCw0OTcwMDAsMjEwMDAsOTAwMDAwLDc2MzAwMCwzMjcwMDAsNDkwMDAwLDEyODMwMDAsMjU4MjAwMCw0ODE4MDAwLDI2NTIwMDAsNzc2MDAwLDk4NjAwMCwyMTAwMCwxODE0MDAwLDI5NjEwMDAsNDM3NzAwMCwyNzU2MDAwLDEwMDAsMjEwMDAsMTU0MDAwMCwxMzIzMDAwLDEyMTMwMDAsMTMzMDAwLDI3OTIwMDAsMjEwMDAsNzkwMDAwLDU2OTAwMCw4MTcwMDAsMTg0MDAwMCwyMTAwMCwxNTIwMDAsMTU3MzAwMCwxMzc1MDAwLDIwMTUwMDAsNTg3MDAwLDM0OTkwMDAsMTE1ODAwMCw0NjMzMDAwLDMyMTcwMDAsNDU1MDAwMCwzODE0MDAwLDI0MDAwLDU5MDAwMCwxNTQwMDAsMjEwMDAsNDA0MjAwMCwyMTAwMCwxOTgwMDAsODEwMDAwLDM2MjAwMCwyNTEwMDAsNzYzMDAwLDMxMTAwMCwyMzgzMDAwLDM4MzUwMDAsMjE4MjAwMCwyMTAwMCwyMTgwMDAwLDEzMzAwMCwyMTAwMCwzNzMwMDAsNjc2MDAwLDgxMDAwMCwzNjA2MDAwLDIxMDAwLDUwNzAwMCw2OTAwMDAsMTkwODAwMCwxODU5MDAwLDM0MzEwMDAsODkwMDAwLDEyODMwMDAsMzMzMDAwMCw0MjQ5MDAwLDQxMTQwMDAsMjEwMDAsMjgwNDAwMCwyMjA0MDAwLDIxMDAwLDIxMDAwLDQzNjIwMDAsMjEwMDAsMjAwNjAwMCwxNTkyMDAwLDM5MTQwMDAsMjAxMzAwMCwyODI3MDAwLDEwMTEwMDAsMjc3MzAwMCwyNzYxMDAwLDIxMDAwLDE5OTkwMDAsMTIwOTAwMCwxNTUwMDAsMTMxNDAwMCwzODY1MDAwLDExMzIwMDBdLCJvcHMiOjE1MzAzMDB9LHsibmFtZSI6IkZpbmQgaXRlbSA0MDAiLCJjb2RlIjoicGFyc2VUcnVuYygtMS45KSIsInJ1bnMiOlsyMDQyMDAwLDkwMDAsMTY0ODAwMCwyNzQ5MDAwLDIyMDAwLDY5NTAwMCw5MDAwLDEzMTQwMDAsNTY3MDAwLDQ4MzAwMCw5MDAwLDEzNzAwMCw0MDAwMDAsMTUwMjAwMCw3NzUwMDAsMjU1NDAwMCwzMTAxMDAwLDIyMDAwLDIzNzIwMDAsMjAyNDAwMCwxMDAwLDE4MTQwMDAsMTAxMDAwMCw2NDQwMDAsMTgyMDAwMCwzMDEwMDAsMjIxNTAwMCw0ODEwMDAsMTU4NDAwMCwyMTMwMDAwLDIyNjMwMDAsNTA3MDAwLDc2MjAwMCwzMDQ0MDAwLDk3NTAwMCw5MDAwLDEzNjIwMDAsMTczNzAwMCw4NjcwMDAsMTU5NzAwMCwyMjY1MDAwLDgyODAwMCw3MjQwMDAsMzYyMDAwLDIwMDAsODkwMDAsOTAwMCwyNDU3MDAwLDExMTkwMDAsMTc5MzAwMCwxMzUxMDAwLDkwMDAsMjIwMDAsMTAwMDAsMTM2MDAwLDEwNDgwMDAsNDQyMDAwLDI3NDEwMDAsMjAwODAwMCw1MjYwMDAsMTc3NTAwMCwzNTEwMDAsMTgyMzAwMCw5MDAwLDI3NTMwMDAsNDQ3MDAwLDg4MzAwMCwyNzY1MDAwLDI1NTcwMDAsMTY2MDAwMCw4NzAwMDAsNTA5MDAwLDEyNzAwMCw5MDAwLDE3OTQwMDAsMzI0MDAwLDM2MjAwMCwxNTYwMDAwLDE4NTIwMDAsNTIwMDAwLDE2MTUwMDAsNTAxMDAwLDkwMDAsMjA2NDAwMCw0ODQwMDAsNzAyMDAwLDI0MDAwLDIxMDAwLDIzNjUwMDAsMjIwMDAsMzA3MDAwMCwyMjAwMCw2NzkwMDAsMjE2NjAwMCwyNDkzMDAwLDE3NzUwMDAsMTM3OTAwMCwyMjI2MDAwLDIyMDAwLDIyMjAwMF0sIm9wcyI6MTEwMzA5MH1dLCJ1cGRhdGVkIjoiMjAyMS0wOS0wN1QwNDo0MzozOC42NThaIn0%3D)

2021-09-07 04:56 UTC, kossnocorp commented on src/_lib/roundingMethods/index.ts
> +export const defaultRoundingMethod = 'trunc'
```suggestion
export const defaultRoundingMethod : RoundingMethod = 'trunc'
```

2021-09-16 05:10 UTC, kossnocorp approved these changes

2021-09-16 05:10 UTC, kossnocorp commented on src/differenceInHours/index.ts
> + * @param {RoundingMethod} roundingMethod - the rounding method (`ceil`, `floor`, `round` or `trunc`) with `trunc` by default.
```suggestion
 * @param {String} roundingMethod - the rounding method (`ceil`, `floor`, `round` or `trunc`) with `trunc` by default.
```

2021-09-16 05:10 UTC, kossnocorp commented on src/differenceInMinutes/index.ts
> + * @param {RoundingMethod} roundingMethod - the rounding method (`ceil`, `floor`, `round` or `trunc`) with `trunc` by default.
```suggestion
 * @param {String} roundingMethod - the rounding method (`ceil`, `floor`, `round` or `trunc`) with `trunc` by default.
```

2021-09-16 05:10 UTC, kossnocorp commented on src/differenceInQuarters/index.ts
> + * @param {RoundingMethod} roundingMethod - the rounding method (`ceil`, `floor`, `round` or `trunc`) with `trunc` by default.
```suggestion
 * @param {String} roundingMethod - the rounding method (`ceil`, `floor`, `round` or `trunc`) with `trunc` by default.
```

2021-09-16 05:10 UTC, kossnocorp commented on src/differenceInSeconds/index.ts
> + * @param {RoundingMethod} roundingMethod - the rounding method (`ceil`, `floor`, `round` or `trunc`) with `trunc` by default.
```suggestion
 * @param {String} roundingMethod - the rounding method (`ceil`, `floor`, `round` or `trunc`) with `trunc` by default.
```

2021-09-16 05:10 UTC, kossnocorp commented on src/differenceInWeeks/index.ts
> + * @param {RoundingMethod} roundingMethod - the rounding method (`ceil`, `floor`, `round` or `trunc`) with `trunc` by default.
```suggestion
 * @param {String} roundingMethod - the rounding method (`ceil`, `floor`, `round` or `trunc`) with `trunc` by default.
```

2021-09-16 05:12 UTC, kossnocorp commented on src/differenceInQuarters/index.ts
> +import type { RoundingMethod } from 'src/types'
```suggestion
import type { RoundingMethod } from '../types'
```

2021-09-16 05:13 UTC, kossnocorp commented on src/differenceInMinutes/index.ts
> +import type { RoundingMethod } from 'src/types'
```suggestion
import type { RoundingMethod } from '../types'
```

2021-09-16 05:13 UTC, kossnocorp commented on src/differenceInSeconds/index.ts
> +import type { RoundingMethod } from 'src/types'
```suggestion
import type { RoundingMethod } from '../types'
```

2021-09-16 05:13 UTC, kossnocorp commented on src/differenceInSeconds/index.ts
> +import type { RoundingMethod } from 'src/types'
```suggestion
import type { RoundingMethod } from '../types'
```

2021-09-16 05:14 UTC, kossnocorp commented on src/differenceInWeeks/index.ts
> +import type { RoundingMethod } from 'src/types'
```suggestion
import type { RoundingMethod } from '../types'
```

2021-09-16 05:14 UTC, kossnocorp commented on src/differenceInHours/index.ts
> +import type { RoundingMethod } from '../../src/types'
```suggestion
import type { RoundingMethod } from '../types'
```

2021-09-16 05:15 UTC, kossnocorp commented on src/differenceInHours/index.ts
> +import type { RoundingMethod } from '../../src/types'
```suggestion
import type { RoundingMethod } from '../types'
```

2021-09-16 21:45 UTC, tan75 approved these changes

2021-09-17 05:24 UTC, merged