ja i18n: use ヶ not か for month counts
date-fns/date-fns pull request #2585
Opened 2021-08-10 18:59 UTC by osdiab

While they're pronounced the same, when written Japanese month counts usually are written with the ヶ character, not the hiragana か. I checked with my native Japanese speaking wife, she says that while か isn't strictly wrong it's not what she would use naturally, and i've never seen it not written with ヶ in my time living in Japan.

https://en.wikipedia.org/wiki/Small_ke

2021-08-12 16:25 UTC, JhonySpark approved these changes

2021-08-12 23:19 UTC, tan75 commented
hi @date-fns/i18n-ja 
could you please have a look and approve this PR?

2021-08-12 23:25 UTC, tan75 requested changes
hi @osdiab 
thank you for your PR! 
Could you please run `yarn locale-snapshots` and commit the results? 
This will help to pass the tests.

2021-08-13 01:29 UTC, ykzts commented
Although "1か月" and "1ヶ月" have the same meaning, "ヶ" is an abbreviation of "箇" and is not often used in official situations.

see also https://en.wiktionary.org/wiki/%E3%83%B6

2021-08-13 06:08 UTC, mesqueeb commented
I guess we should make it configurable by the developer in some way.

2021-12-27 23:28 UTC, tan75 commented
hi @date-fns/i18n-ja 
is this PR to go ahead? Or should I close it?

2021-12-27 23:50 UTC, mesqueeb commented
@tan75  か is more correct so should be the default. In case the user wants ヶ they can simply do a text replacement.

I feel like making this configurable in date-fns can be considered but will require tremendous effort thinking of implementation syntax. 

You have my vote to close this PR without changes.

2022-01-07 12:09 UTC, closed without merging