convert `getWeekOfMonth` to TypeScript
date-fns/date-fns pull request #2598
Opened 2021-08-17 15:23 UTC by fturmel

Closes https://github.com/date-fns/date-fns-typescriptify/issues/59

Oddly, there has been 3 abandoned PR for this TS conversion (#2238, #2146, #2332). Hopefully this is the right one!

I tried to simplify the code a bit, and added a test to raise coverage to 100%.

2021-09-10 21:08 UTC, tan75 commented on src/getWeekOfMonth/index.ts
> +import { LocaleOptions, WeekStartOptions } from '../types'
```suggestion
import type { LocaleOptions, WeekStartOptions } from '../types'
```

2021-09-11 18:23 UTC, tan75 requested changes
Hi! Thank you for this PR! 🙏
Could you please address my comments?

2021-09-11 18:23 UTC, tan75 commented on src/getWeekOfMonth/index.ts
> +  const weekStartsOn =
It looks like you changed the logic here. Could you please restore the previous logic?

2021-09-12 17:26 UTC, fturmel commented on src/getWeekOfMonth/index.ts
> +  const weekStartsOn =
All tests are passing, the behavior looks the same to me even though it's been simplified. Could you point out specifically where the problem is?

2021-09-12 17:27 UTC, fturmel commented on src/getWeekOfMonth/index.ts
> +import { LocaleOptions, WeekStartOptions } from '../types'
Done

2021-12-13 13:55 UTC, fturmel commented
Rebased + suppress a TS error in the test file that I had missed before

2021-12-21 17:34 UTC, leshakoss commented on src/getWeekOfMonth/index.ts
> +  const weekStartsOn =
Ok I tested this manually and seems like the only difference is `{ weekStatsOn: null }`. Dropping this is fine for v3 but it would be a breaking change for v2. Fixed in the commit: https://github.com/date-fns/date-fns/pull/2598/commits/e081fcf0b6dbaf2b40d348fa45cc26e4bcc6cb04

2021-12-21 17:35 UTC, leshakoss approved these changes
Thanks a lot!

2021-12-21 17:54 UTC, merged

2021-12-21 18:02 UTC, leshakoss commented on src/getWeekOfMonth/index.ts
> +  const weekStartsOn =
BTW @tan75 👀