added it-CH locale
date-fns/date-fns pull request #2886
Opened 2021-12-28 15:33 UTC by maic66

Please be patient if I did some mistakes, it's my first PR contribution.

2021-12-28 17:40 UTC, fturmel requested changes
LGTM! See my comment about the missing jsdoc annotation.

2021-12-29 10:39 UTC, maic66 reviewed
added missing jsdoc annotation

2021-12-29 10:40 UTC, maic66 commented on src/locale/it-CH/index.ts
> + * @language Italian
added missing jsdoc annotation

2021-12-29 13:06 UTC, fturmel approved these changes

2022-01-10 20:07 UTC, merged

2022-01-11 07:12 UTC, Spinnenzunge commented
Thank you very much 💋

2022-02-23 15:29 UTC, maic66 commented
I've seen this was a late merge and it's still not reflected in npm package.
How does it work?

2022-02-24 14:01 UTC, fturmel commented
@maic66 there just hasn't been an official release since the PR was merged. I don't know for sure, but it seems like there is only one task holding off the next release #2887

2022-05-10 11:33 UTC, maic66 commented
Hi all. I updated my npm packages but this commit is still not present.
Has somebody an explanation for this?