Fixed constants TS typings
date-fns/date-fns pull request #2941
Opened 2022-02-01 03:35 UTC by JuanM04

Re-added `src/constants/index.d.ts` and added module definitions to `typings.d.ts`

2022-02-01 14:15 UTC, fturmel requested changes
Nice! I also had noticed that the constants `.d.ts` file wasn't automatically generated.

2022-02-01 14:15 UTC, fturmel commented on scripts/build/_lib/typings/typeScript.js
> +function getTypeScripttConstantsModuleDefinition(constants, fnSuffix) {
Little typo here, two `t`s in TypeScript

2022-02-01 14:22 UTC, JuanM04 commented on scripts/build/_lib/typings/typeScript.js
> +function getTypeScripttConstantsModuleDefinition(constants, fnSuffix) {
Nice catch, thanks

2022-02-01 14:58 UTC, fturmel approved these changes

2022-06-23 09:54 UTC, leshakoss approved these changes
Thank you so much!

2022-06-23 09:55 UTC, merged