Implement getDefaultOptions, setDefaultOptions
date-fns/date-fns pull request #3069
Opened 2022-05-31 18:47 UTC by leshakoss

- [ ] Explain in the docs why default options are limited in scope to options and week year stuff
- [ ] Add argument and return types
- [ ] Write tests for getDefaultOptions
- [ ] Write tests for setDefaultOptions
- [ ] Verify that FP generator doesn't freak out

2022-06-11 01:47 UTC, kossnocorp commented on src/endOfWeek/index.ts
> +  )
I'm comparing this PR to https://github.com/date-fns/date-fns/pull/3087 and this one, with the wider scope, feels more future-prone.

If we decide to move locales to separate packages and make `Intl` the default approach, the change will still make sense. Furthermore, we might think of option autodetection and apply user-specific defaults for `weekStartsOn`, which would be impossible if we stick to locale-only.

It is indeed more code, but we can approach it slightly differently and reduce it to something like:

```suggestion
  const weekStartsOn = getOption(options, 'weekStartsOn')
```

That will also help to abstract the default behavior that we repeat from function to function.

2022-06-11 01:53 UTC, kossnocorp requested changes

2022-06-11 01:53 UTC, kossnocorp commented on src/_lib/defaultOptions/index.ts
> +export let _defaultOptions: AllOptions = {}
This approach doesn't feel safe, let's use a getter function instead. Module exports are supposed to be static if I'm not mistaken and modifying it might break them. Also `getOptions` looks better than `_defaultOptions`.

2022-06-11 01:53 UTC, kossnocorp commented on src/_lib/defaultOptions/index.ts
> +  AreIntervalsOverlappingOptions
Maybe we don't need to make **all** options global, but `locale`, `weekStartsOn`, etc.

2022-06-23 08:41 UTC, leshakoss commented on src/_lib/defaultOptions/index.ts
> +  AreIntervalsOverlappingOptions
Reduced the scope to the big three: locale, weekStartsOn, firstWeekContainsDate

2022-06-23 08:48 UTC, kossnocorp commented on src/formatDuration/index.ts
> +  const delimiter = options?.delimiter ?? ' '
I'm afraid that this can be a breaking change, but I don't mind it haha

2022-06-23 08:49 UTC, kossnocorp commented on src/formatISO/test.ts
> +export function generateOffset(originalDate: Date) {
Maybe move it to the `src/_lib/test/index.ts`?

2022-06-23 08:53 UTC, kossnocorp approved these changes
Look goods except for exsessive usage of `??` that might alter behavior. I don't mind shipping it as is because it's better for the future.

2022-06-23 09:40 UTC, merged

2022-07-09 00:40 UTC, olee commented
When might we expect a new version to be published with those changes, if I dare to ask? :-)

2022-07-22 08:33 UTC, leshakoss commented
This closed  #816

2022-07-22 12:18 UTC, leshakoss commented
@olee published in v2.29: https://github.com/date-fns/date-fns/releases/tag/v2.29.1