Fixes ESM import in Node.js
date-fns/date-fns pull request #3099
Opened 2022-06-27 07:21 UTC by ocavue

Close https://github.com/date-fns/date-fns/issues/2964

2022-06-27 10:28 UTC, kossnocorp requested changes
It breaks CommonJS support.

You can check it by running `./scripts/build/package.sh` and then trying to import `require('./tmp/package')`

![image](https://user-images.githubusercontent.com/52201/175921152-fb043bc6-5887-43b3-b67b-f1fb5f6c8f31.png)

2022-06-27 15:13 UTC, ocavue commented
@kossnocorp Fixed. I also listed all updated files under the PR description to make sure I didn't touch CJS part unexpectedly.

2022-07-08 10:34 UTC, kossnocorp requested changes
Hey, thank you for the fix!

There's still a problem with FP submodule:

![image](https://user-images.githubusercontent.com/52201/177975984-3f4ad632-da2e-4e69-8aa4-5832cc5c1c89.png)

I added an example test that you can run:

```bash
cd examples/node-esm
yarn
yarn run build
yarn test
```

2022-10-06 12:46 UTC, productdevbook commented
Is this issue still going on, I have the same error.

2023-06-02 01:41 UTC, longnguyen2004 commented
How is this PR going? Just got hit with this myself too.

2023-10-05 19:43 UTC, steve-todorov commented
@kossnocorp / @ocavue is there anything more needed to be done with this PR or can it be merged and released?  :)

2023-11-11 18:34 UTC, MickL commented
Can this get merged please?

2023-11-13 02:08 UTC, kossnocorp commented
Node.js ESM support is coming in v3. The build update's already implemented in the `main` branch. Thank you everyone for the input.

2023-11-13 02:08 UTC, closed without merging